INSERT INTO clients (
    first_name, last_name, email, phone, mobile, tax_id, birth_date, 
    address, city, state, postal_code, country, notes, status, external_id
) VALUES 
    ('PEDRO', 'MIGUEL MORAIS GONÇALVES', 'moraisportugal@gmail.com', NULL, NULL, NULL, NULL, NULL, '4780-367 SANTO TIRSO', NULL, NULL, 'Brasil', NULL, 'active', 'bd_1'),
    ('LADJANE', 'CONOLLY GOMES - CONF. DIVIDA - DD DR. TIAGO', 'fabiohcgomes@gmail.com', NULL, NULL, NULL, NULL, NULL, '4470-334 PORTO', NULL, NULL, 'Brasil', NULL, 'active', 'bd_2'),
    ('LEIA', 'LIBERATO', 'alcirleia.12bp@gmail.com', NULL, NULL, NULL, NULL, NULL, '4200-366 Porto', NULL, NULL, 'Brasil', NULL, 'active', 'bd_3'),
    ('DULCE', 'JOÃO BERNARDINO MOREIRAS', 'dulcemoreiras78@gmail.com', NULL, NULL, NULL, NULL, NULL, '4445-126 ALFENA', NULL, NULL, 'Brasil', NULL, 'active', 'bd_4'),
    ('MAGALI', ' ALVES DE OLIVEIRA', 'magaadv2017@gmail.com', NULL, NULL, NULL, NULL, NULL, '4400-004 VILA NOVA DE GAIA', NULL, NULL, 'Brasil', NULL, 'active', 'bd_5'),
    ('MILENE', 'SOARES VIEIRA', 'milenevieira_fv@hotmail.com', NULL, NULL, NULL, NULL, NULL, '4575-177 CANELAS', NULL, NULL, 'Brasil', NULL, 'active', 'bd_6'),
    ('MIRIAN', 'CAVALCANTE  PEREIRA -  RENEGOCIAÇÃO AUTORIZADA PELA DRA ARE', NULL, NULL, NULL, NULL, NULL, NULL, '4000-307 PORTO', NULL, NULL, 'Brasil', NULL, 'active', 'bd_7'),
    ('FELIPE', 'CABRAL - DESCONTO EM FOLHA DE PAGAMENTO NICAELA', 'felipecabral.adv@gmail.com', NULL, NULL, NULL, NULL, NULL, '4000-457 PORTO', NULL, NULL, 'Brasil', NULL, 'active', 'bd_8'),
    ('ELAINE', 'FERREIRA ARAÚJO - DRA DAIANE', 'lanagi314hotmail.com', NULL, NULL, NULL, NULL, NULL, '4400-345 VILA NOVA DE GAIA', NULL, NULL, 'Brasil', NULL, 'active', 'bd_9'),
    ('RUI', 'MANUEL DE ABREU MARTINS', 'ruiabreumartins62@gmail.com', NULL, NULL, NULL, NULL, NULL, '92-51 DIEKIRCH – LUXEMBURGO', NULL, NULL, 'Brasil', NULL, 'active', 'bd_10'),
    ('ISAAC', 'LUCAS CAVALCANTE DA SILVA', 'isaacdasilva_15@outlook.pt', NULL, NULL, NULL, NULL, NULL, '4100-175 PORTO', NULL, NULL, 'Brasil', NULL, 'active', 'bd_11'),
    ('MARIA', 'CRISTINA FONSECA OLIVEIRA FIGUEIREDO', 'INFO@FCCONSEILS.CH', NULL, NULL, NULL, NULL, NULL, '151-0 MOUNDON, SUIÇA', NULL, NULL, 'Brasil', NULL, 'active', 'bd_12'),
    ('MARIA', 'CLEICIANE FERREIRA TELES', 'annetelles_12@hotmail.com', NULL, NULL, NULL, NULL, NULL, 'PORTO - PORTUGAL', NULL, NULL, 'Brasil', NULL, 'active', 'bd_13'),
    ('LARISSA', 'GLEISLA DA SILVA  NOGUEIRA', 'LARISSAGLEYSLA@GMAIL.COM', NULL, NULL, NULL, NULL, NULL, '4250-295 PORTO', NULL, NULL, 'Brasil', NULL, 'active', 'bd_14'),
    ('MARIA', 'DE FATIMA NEVES FERREIRA', 'FATIMA.NUNES822@GMAIL.COM', NULL, NULL, NULL, NULL, NULL, '4540-219 Poços Burgo', NULL, NULL, 'Brasil', NULL, 'active', 'bd_15'),
    ('ANA', 'CRISTINA LOUREIRO ALVES', 'ana_riis@hotmail.com', NULL, NULL, NULL, NULL, NULL, '4510-548 FÂNZERES', NULL, NULL, 'Brasil', NULL, 'active', 'bd_16'),
    ('RITA', 'FABIANA BATISTA DA SILVA', 'ritinhajiujitshu@hotmail.com', NULL, NULL, NULL, NULL, NULL, '4445-204 ALFENA', NULL, NULL, 'Brasil', NULL, 'active', 'bd_17'),
    ('RENATA', 'CRISTINA COSTA GOMES', 'gomes_rcc@hotmail.com', NULL, NULL, NULL, NULL, NULL, '4400-346 VILA NOVA DE GAIA', NULL, NULL, 'Brasil', NULL, 'active', 'bd_18'),
    ('ROSANIA', 'MARIA SOUSA E SILVA', 'rosania.souza37@gmail.com', NULL, NULL, NULL, NULL, NULL, '4410-456 ARCOZELO - VILA NOVA DE GAIA', NULL, NULL, 'Brasil', NULL, 'active', 'bd_19'),
    ('OLGA', 'MARIA CORREIA', 'olgavieira105@gmail.com', NULL, NULL, NULL, NULL, NULL, '4250-291 PORTO', NULL, NULL, 'Brasil', NULL, 'active', 'bd_20'),
    ('FLAVIA', 'DANIELA MARTINS SILVA', 'flaviadaniela0009@gmail.com', NULL, NULL, NULL, NULL, NULL, '4420-286 Gondomar', NULL, NULL, 'Brasil', NULL, 'active', 'bd_21'),
    ('SORAIA', 'RAQUEL MOUTINHO ANUNCIAÇÃO', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Brasil', NULL, 'active', 'bd_22'),
    ('DRIELLY', 'MAGNO DE SOUZA', 'mixbelly.ds@gmail.com', NULL, NULL, NULL, NULL, NULL, '4455-596 PERAFITA', NULL, NULL, 'Brasil', NULL, 'active', 'bd_23'),
    ('MARTA', 'MARIA FERREIRA RODRIGUES', 'martamaria.porto@hotmail.com', NULL, NULL, NULL, NULL, NULL, '4465-092 SÃO MAMEDE DE INFESTA', NULL, NULL, 'Brasil', NULL, 'active', 'bd_24'),
    ('GLEICIANE', 'LIMA SOBRINHO - FATURAR NO MARIDO HENRIQUE MANUEL SÁ REBELO 1967', 'gleician3@hotmail.com', NULL, NULL, NULL, NULL, NULL, '4300-293 PORTO', NULL, NULL, 'Brasil', NULL, 'active', 'bd_25'),
    ('JOANA', 'DE SAMPAIO MARTINS', 'sampaioemeloj@gmail.com', NULL, NULL, NULL, NULL, NULL, '6420-053 TRANCOSO', NULL, NULL, 'Brasil', NULL, 'active', 'bd_26'),
    ('RICARDO', 'FILIPE BARBOSA PEREIRA', 'katianemascena@hotmail.com', NULL, NULL, NULL, NULL, NULL, '4400-649 VILA NOVA DE GAIA', NULL, NULL, 'Brasil', NULL, 'active', 'bd_27'),
    ('JOÃO', 'VITOR WEIGERT GONÇALVES', 'jvwgoncalves@gmail.com', NULL, NULL, NULL, NULL, NULL, '4100-242 PORTO', NULL, NULL, 'Brasil', NULL, 'active', 'bd_28'),
    ('FERNANDA', 'ELISA PONDE BRITO', 'fernandaponde@gmail.com', NULL, NULL, NULL, NULL, NULL, '4100-341 PORTO', NULL, NULL, 'Brasil', NULL, 'active', 'bd_29'),
    ('MARIA', 'MÁXIMA VIANA', 'midiogo@hotmail.com', NULL, NULL, NULL, NULL, NULL, '4000-364 PORTO', NULL, NULL, 'Brasil', NULL, 'active', 'bd_30'),
    ('ELISABETE', 'CRISTINA TEIXEIRA COELHO', 'e_ccoelho@hotmail.com', NULL, NULL, NULL, NULL, NULL, '4435-277 RIO TINTO', NULL, NULL, 'Brasil', NULL, 'active', 'bd_31'),
    ('PEDRO', 'MANUEL MORGADO LEITE - CAPILAR', 'pedrommleite833@gmail.com', NULL, NULL, NULL, NULL, NULL, '- PORTUGAL', NULL, NULL, 'Brasil', NULL, 'active', 'bd_32'),
    ('BARBARA', 'SALGADO - DRA. DAIANE CONF. DÍVIDA DÍVIDA', 'barbarasolange92@gmail.com', NULL, NULL, NULL, NULL, NULL, '4425-632 MAIA', NULL, NULL, 'Brasil', NULL, 'active', 'bd_33'),
    ('CINTIA', 'PEREIRA - KARINNY PEREIRA - DR. ROBERTO- SÓ CONTRATO', 'cintiaske@gmail.com', NULL, NULL, NULL, NULL, NULL, '4400-542 VILA NOVA DE GAIA', NULL, NULL, 'Brasil', NULL, 'active', 'bd_34'),
    ('MARCIO', 'DANIEL TEIXEIRA DA COSTA - DRA ALINE MARODIN', 'MARCIOCOSTACORSA@GMAIL.COM', NULL, NULL, NULL, NULL, NULL, '0000-13109 MARSELLE - FRANÇA', NULL, NULL, 'Brasil', NULL, 'active', 'bd_35'),
    ('RONALDO', 'JUNIO DE SOUSA - CAPILAR', NULL, NULL, NULL, NULL, NULL, NULL, '- PORTUGAL', NULL, NULL, 'Brasil', NULL, 'active', 'bd_36'),
    ('DANIEL', 'RODRIGO GOMES CARVALHO MATOS', 'DANIEL-RGC@HOTMAIL.COM', NULL, NULL, NULL, NULL, NULL, '4605-307 VILA MEÃ', NULL, NULL, 'Brasil', NULL, 'active', 'bd_37'),
    ('LISETE', 'ALVES DE OLIVEIRA', 'lisetealvesdeoliveira@gmail.com', NULL, NULL, NULL, NULL, NULL, '4520-455 CASAIS', NULL, NULL, 'Brasil', NULL, 'active', 'bd_38'),
    ('JOÃO', 'PEREIRA FARIA DE CARIA', 'joao_caria@hotmail.com', NULL, NULL, NULL, NULL, NULL, '4775-092 FONTE COBERTA - BRAGA', NULL, NULL, 'Brasil', NULL, 'active', 'bd_39'),
    ('JESSICA', 'BRUNA DA SILVA MENDES', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Brasil', NULL, 'active', 'bd_40'),
    ('HELTON', 'RODRIGUES DOS SANTOS', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Brasil', NULL, 'active', 'bd_41'),
    ('JOSÉ', 'ANTONIO MARINHO MEIRELES RUAO', 'JOSERUAO@OUTLOOK.COM', NULL, NULL, NULL, NULL, NULL, '473071-3 VILA VERDE', NULL, NULL, 'Brasil', NULL, 'active', 'bd_42'),
    ('MARIA', 'EMILIA TEIXEIRA - CONF. DÍVIDA - DR. ROBERTO - DD', NULL, NULL, NULL, NULL, NULL, NULL, '0000-1860 SUIÇA', NULL, NULL, 'Brasil', NULL, 'active', 'bd_43'),
    ('ELIANE', 'DA SILVA LIMA', 'lyalyma2525@gmail.com', NULL, NULL, NULL, NULL, NULL, '4435-241 RIO TINTO', NULL, NULL, 'Brasil', NULL, 'active', 'bd_44'),
    ('MARIA', 'DE FÁTIMA TOMAS - DRA.  ALINE.-  CONTRATO', 'fatimaptomas@gmail.com', NULL, NULL, NULL, NULL, NULL, '2200-117 ABRANTES', NULL, NULL, 'Brasil', NULL, 'active', 'bd_45'),
    ('ROGERIO', 'ROCHA', NULL, NULL, NULL, NULL, NULL, NULL, '4710-353 BRAGA', NULL, NULL, 'Brasil', NULL, 'active', 'bd_46'),
    ('HELDER', 'RIBEIRO (IMPLANTES) DRA. ALINE - CONF. DIVIDA', NULL, NULL, NULL, NULL, NULL, NULL, '4745-373 SÃO MAMEDE CORONADO', NULL, NULL, 'Brasil', NULL, 'active', 'bd_47'),
    ('LEANDRA', 'EPIFÂNIA GUEDES PEREIRA TEIXEIRA ALVES', 'paula.pguedes@gmail.com', NULL, NULL, NULL, NULL, NULL, '4460-384 SENHORA DA HORA', NULL, NULL, 'Brasil', NULL, 'active', 'bd_48'),
    ('MARCIO', 'JOSE GONÇALVES DA SILVA        DD', 'marciosilva866@hotmail.com', NULL, NULL, NULL, NULL, NULL, '4425-040 MAIA', NULL, NULL, 'Brasil', NULL, 'active', 'bd_49'),
    ('ALBERTO', 'PAULO MOURA DA SILVA', NULL, NULL, NULL, NULL, NULL, NULL, '4600-017 AMARANTE', NULL, NULL, 'Brasil', NULL, 'active', 'bd_50'),
    ('ECILENE', ' KAYLLEY  COSTA     DD - CONF. DÍVIDA', 'ribeirokayllley@gmail.com', NULL, NULL, NULL, NULL, NULL, '4460-481 MATOSINHOS', NULL, NULL, 'Brasil', NULL, 'active', 'bd_51'),
    ('MICHELE', 'BIANCA DE SOUZA GIELOW IBANEZ', 'michele.ibanez81@gmail.com', NULL, NULL, NULL, NULL, NULL, '4715-505 BRAGA', NULL, NULL, 'Brasil', NULL, 'active', 'bd_52'),
    ('ANDREIA', 'SOFIA LOPES VIEIRA', 'asvieira2109@hotmail.com', NULL, NULL, NULL, NULL, NULL, '6660-000 LUXEMBURGO', NULL, NULL, 'Brasil', NULL, 'active', 'bd_53'),
    ('GEYZA', 'MYCHELY DA SILVA', 'geyzaoliveira202@gmail.com', NULL, NULL, NULL, NULL, NULL, 'PORTO - PORTUGAL', NULL, NULL, 'Brasil', NULL, 'active', 'bd_54'),
    ('TERESA', 'MARIA DA ROCHA VENTURA SILVA OLIVEIRA DIAS', 'TV.TERESAVENTURA@GMAIL.COM', NULL, NULL, NULL, NULL, NULL, '4050-318 PORTO', NULL, NULL, 'Brasil', NULL, 'active', 'bd_55'),
    ('EMMANUELLE', 'SUDRE', 'emmanuelle.f.sudre@gmail.com', NULL, NULL, NULL, NULL, NULL, '4250-164 PORTO', NULL, NULL, 'Brasil', NULL, 'active', 'bd_56'),
    ('TERESA', 'MADEIRA - CONF. DÍVIDA - DRA. ALINE - DD', 'ana.valente@grupomaroliv.com', NULL, NULL, NULL, NULL, NULL, '4150-326 PORTO', NULL, NULL, 'Brasil', NULL, 'active', 'bd_57'),
    ('ERIVAN', 'DIOGO DA SILVA  - CONF. DÍVIDA - DD. DRA. LU', 'douglas2012gabriel@hotmail.com', NULL, NULL, NULL, NULL, NULL, '4415-490 GRIJÓ', NULL, NULL, 'Brasil', NULL, 'active', 'bd_58'),
    ('PAULA', 'ALEXANDRA SILVA. CONFISSÃO DE DÍVIDA  - DRA. ALINE  - DD', 'ferreira.paulaalexandra@gmail.com', NULL, NULL, NULL, NULL, NULL, '4000-488 PORTO', NULL, NULL, 'Brasil', NULL, 'active', 'bd_59'),
    ('SUZANA', 'CAMARGO DA SILVA - DR. ROBERTO ALMEIDA', 'sula.camargo.84@gmail.com', NULL, NULL, NULL, NULL, NULL, '4415-158 PEDROSO', NULL, NULL, 'Brasil', NULL, 'active', 'bd_60'),
    ('RICARDO', 'JORGE CASTRO - CONF. DÍVIDA - TB COM NIF - DRA. ALINE', 'ricardojorgecastro.73@gmail.com', NULL, NULL, NULL, NULL, NULL, '4435-148 RIO TINTO', NULL, NULL, 'Brasil', NULL, 'active', 'bd_61'),
    ('PATRICIA', 'TAVARES BLANCO', 'pattitavares@gmail.com', NULL, NULL, NULL, NULL, NULL, '4480-107 ÁRVORE', NULL, NULL, 'Brasil', NULL, 'active', 'bd_62'),
    ('ALEXANDRE', 'MIGUEL GOMES VELOSO', 'veloso1975@hotmail.com', NULL, NULL, NULL, NULL, NULL, '2732-0 MARCILLY-LA-CAMPAGNE', NULL, NULL, 'Brasil', NULL, 'active', 'bd_63'),
    ('SANDRA', 'MARISA DE SOUSA LATÃES', 'smarisa28@hotmail.com', NULL, NULL, NULL, NULL, NULL, '4745-473 SÃO MAMEDE CORONADO', NULL, NULL, 'Brasil', NULL, 'active', 'bd_64'),
    ('LUIS', 'FILIPE MARQUES DA COSTA - CONF. DÍVIDA - DR. ROBERTO - DD', 'dacostacarrelage@hotmail.com', NULL, NULL, NULL, NULL, NULL, '2530-101 LOURINHÃ', NULL, NULL, 'Brasil', NULL, 'active', 'bd_65'),
    ('PAULO', 'JORGE MARQUES - ESPOSA SILVIA - CONF. DÍVIDA DRA. ALINE - DD OU TB', 'paulojorgemarques3@gmail.com', NULL, NULL, NULL, NULL, NULL, '0000-1030 BÉLGICA', NULL, NULL, 'Brasil', NULL, 'active', 'bd_66'),
    ('ISABEL', 'MARGARIDA FAJARDO MOIO - CONF. DÍVIDA - DRA. ALINE - DD', 'isabel.fajardo.moio1969@gmail.com', NULL, NULL, NULL, NULL, NULL, '0000-L-4171 LUXEMBURGO', NULL, NULL, 'Brasil', NULL, 'active', 'bd_67'),
    ('ANA', 'MARGARIDA CACHO ESTEVES', 'ritinha8simoes@gmail.com', NULL, NULL, NULL, NULL, NULL, '4050-306 PORTO', NULL, NULL, 'Brasil', NULL, 'active', 'bd_68'),
    ('SANDRA', 'GUERRA - DÉBITO DIRETO - FATURAR DD', 'sandraguerra765@gmail.com', NULL, NULL, NULL, NULL, NULL, '0000-1921 SUIÇA', NULL, NULL, 'Brasil', NULL, 'active', 'bd_69'),
    ('ANA', 'CRISTINA MENDES SEMEDO', 'semedoana34@gmail.com', NULL, NULL, NULL, NULL, NULL, '2635-184 RIO DE MOURO', NULL, NULL, 'Brasil', NULL, 'active', 'bd_70'),
    ('SAMUEL', 'BATISTA FERNANDES', 'samuka_271@hotmail.com', NULL, NULL, NULL, NULL, NULL, '92100-000 BILLANCONT - FRANÇA', NULL, NULL, 'Brasil', NULL, 'active', 'bd_71'),
    ('DELMAR', 'AGOSTINHO LOPES - DEFINITIVAS', 'CASARES3@LIVE.FR', NULL, NULL, NULL, NULL, NULL, '5445-082 NOZEDO', NULL, NULL, 'Brasil', NULL, 'active', 'bd_72'),
    ('FILOMENA', 'MARIA DA COSTA NUNES  AMARO - CONF. DÍVIDA - DR. ROBERTO - DD', 'filomena.amaroc@hotmail.com', NULL, NULL, NULL, NULL, NULL, '000-1926 Suiça', NULL, NULL, 'Brasil', NULL, 'active', 'bd_73'),
    ('SONIA', 'MARIA GOULART GONÇALVES', 'goulartsonia@gmail.com', NULL, NULL, NULL, NULL, NULL, '4490-634 POVOA DE VARZIM', NULL, NULL, 'Brasil', NULL, 'active', 'bd_74'),
    ('FREDERICA', 'CAMPOS MONTEIRO - DEFINITIVA', 'f.lourenco@afdb.org', NULL, NULL, NULL, NULL, NULL, '4050-501 PORTO', NULL, NULL, 'Brasil', NULL, 'active', 'bd_75'),
    ('MARIA', 'JOSÉ PINTO DE OLIVEIRA MACHADO - CONTRATO DEFINITIVAS', 'MARIA.MACHADO.MM23@GMAIL.COM', NULL, NULL, NULL, NULL, NULL, '0000-45380 LA CHAPELLE SAINT MESMIN - FRANÇA', NULL, NULL, 'Brasil', NULL, 'active', 'bd_76'),
    ('GILBERTO', 'PASSAGEM - DD ESPOSA LINA - CONF. DÍVIDA -DEFINITIVAS', 'gilbertopassagem50@gmail.com', NULL, NULL, NULL, NULL, NULL, '4959-000 Luxemburgo', NULL, NULL, 'Brasil', NULL, 'active', 'bd_77'),
    ('SANDRA', 'CRISTINA LOPES DE JESUS', 'Jesus.breyd@hotmail.com', NULL, NULL, NULL, NULL, NULL, '0000-2000 SUIÇA', NULL, NULL, 'Brasil', NULL, 'active', 'bd_78'),
    ('PEDRO', 'PORTUGAL GONÇALVES DA MOTA - DRA. ALINE MARODIN', 'ppgm@sapo.pt', NULL, NULL, NULL, NULL, NULL, '5100-143 LAMEGO', NULL, NULL, 'Brasil', NULL, 'active', 'bd_79'),
    ('BENEDITA', 'RODRIGUES VIANA - DEFINITIVA', 'vianabenedita814@gmail.com', NULL, NULL, NULL, NULL, NULL, '4465-276 SÃO MAMEDE DE INFESTA', NULL, NULL, 'Brasil', NULL, 'active', 'bd_80'),
    ('FELISBELA', 'ODETE TEIXEIRA DE SOUSA - DEFINITIVA', 'bela.t.sousa@gmail.com', NULL, NULL, NULL, NULL, NULL, '9071-000 LUXEMBURGO', NULL, NULL, 'Brasil', NULL, 'active', 'bd_81'),
    ('ALESSANDRA', 'CRISTINA TERRES MINETTO', 'alessandraminetto6@gmail.com', NULL, NULL, NULL, NULL, NULL, 'BH8-8NF BOURNEMOUTH - INGLATERRA', NULL, NULL, 'Brasil', NULL, 'active', 'bd_82'),
    ('VICTOR', 'HUGO MAIA - CONF. DÍVIDA- DR. ROBERTO - DD', 'hugomaiamaia1984@gmail.com', NULL, NULL, NULL, NULL, NULL, '4405-934 VILA NOVA DE GAIA', NULL, NULL, 'Brasil', NULL, 'active', 'bd_83'),
    ('DULCE', 'DE SOUSA CORAÇA - DR LEONARDO SARAIVA', 'dulcepraia@gmail.com', NULL, NULL, NULL, NULL, NULL, '4490-405 PÓVOA DE VARZIM', NULL, NULL, 'Brasil', NULL, 'active', 'bd_84'),
    ('SANDRA', 'CRISTINA CERQUEIRA DE MOURA CAMPOS VELOSO - ADITAMENTO', 'sandracampos0909@gmail.com', NULL, NULL, NULL, NULL, NULL, '4250-061 PORTO', NULL, NULL, 'Brasil', NULL, 'active', 'bd_85'),
    ('CRISTINA', 'ELISABETE MAGALHÃES CARNEIRO - DRA ARETHUZA LUNA', 'CRISTINAMACHADO@HOTMAIL.FR', NULL, NULL, NULL, NULL, NULL, '4860-204 BREIA CABEÇEIRA DE BASTOS BRAGA', NULL, NULL, 'Brasil', NULL, 'active', 'bd_86'),
    ('VERA', 'PAULA DA ROCHA LEMOS - DRA ALINE MARODIN (TRANS MARIA MANUELA)', 'veradinis_14@hotmail.com', NULL, NULL, NULL, NULL, NULL, '0000-8625 ZURICH SUIÇA', NULL, NULL, 'Brasil', NULL, 'active', 'bd_87'),
    ('ALESSANDRO', 'SANTANA DE JESUS', 'alessandrosantanadeporto@gmail.com', NULL, NULL, NULL, NULL, NULL, '4430-020 VILA NOVA DE GAIA', NULL, NULL, 'Brasil', NULL, 'active', 'bd_88'),
    ('DANIEL', 'RICARDO SANTOS - FASE DEFINITIVA', 'veradinis_14@hotmail.com', NULL, NULL, NULL, NULL, NULL, '0000-8625 ZURICH', NULL, NULL, 'Brasil', NULL, 'active', 'bd_89'),
    ('MARIA', 'ELISABETE DE SOUSA - DR. ROBERTO - DD', 'betadesousa3@gmail.com', NULL, NULL, NULL, NULL, NULL, '4525-091 SANTA MARIA DA FEIRA', NULL, NULL, 'Brasil', NULL, 'active', 'bd_90'),
    ('GUILHERME', 'DE BRITO MARQUES CARRILHO', 'GUILHERME_CARRILHO41@HOTMAIL.COM', NULL, NULL, NULL, NULL, NULL, '19-08 RIDDES - SUISSE', NULL, NULL, 'Brasil', NULL, 'active', 'bd_91'),
    ('MARGARETH', 'LUIZA PALOMBO PEREIRA (DD Marido 5334)', 'mpalombolyrio@hotmail.com', NULL, NULL, NULL, NULL, NULL, '4500-534 ESPINHO', NULL, NULL, 'Brasil', NULL, 'active', 'bd_92'),
    ('ISABEL', 'FRANCISCO  DOMINGOS- CONF. DÍVIDA - DRA. ALINE - DD (PAGO POR JOAO BAPTISTA MAN / EDNA BAPTISTA)', 'policarpoisabel76@gmail.com', NULL, NULL, NULL, NULL, NULL, '2580-492 CARREGADO E CADAFAIS', NULL, NULL, 'Brasil', NULL, 'active', 'bd_93'),
    ('ROGERIO', 'MANUEL MOREIRA', 'codina.myriam@gmail.com', NULL, NULL, NULL, NULL, NULL, '83136-000 SAINTE -ANASTASIE-SUR-ISSOLE FRANCE', NULL, NULL, 'Brasil', NULL, 'active', 'bd_94'),
    ('DANIELA', 'ALEXANDRA ALCANTARA - DR ROBERTO ALMEIDA', 'DANIELAALEXANDRA.MOREIRADIAS@GMAIL.COM', NULL, NULL, NULL, NULL, NULL, '0000-73700 FRANÇA', NULL, NULL, 'Brasil', NULL, 'active', 'bd_95'),
    ('JORGE', 'CÁSSIO  DANTAS', 'jorgecassiodantas@gmail.com', NULL, NULL, NULL, NULL, NULL, '4450-012 MATOSINHOS', NULL, NULL, 'Brasil', NULL, 'active', 'bd_96'),
    ('VERA', 'LUCIA DA COSTA SILVESTRE', 'verasilvestre078@gmail.com', NULL, NULL, NULL, NULL, NULL, '0000-57390 Audun-le-Tiche France', NULL, NULL, 'Brasil', NULL, 'active', 'bd_97'),
    ('MANUEL', 'AVELINO MACHADO DIAS', 'kelmanulive@gmail.com', NULL, NULL, NULL, NULL, NULL, '4470-145 MAIA', NULL, NULL, 'Brasil', NULL, 'active', 'bd_98'),
    ('CARLA', 'CRISTINA PEREIRA HIPOLITO', 'carlahipolito@hotmail.com', NULL, NULL, NULL, NULL, NULL, 'MK112BA-000 MILTON KEYNES - INGLATERRA', NULL, NULL, 'Brasil', NULL, 'active', 'bd_99'),
    ('ANA', 'LIDIA PEREIRA HIPOLITO - DEFINITIVA', 'anah196923@gmail.com', NULL, NULL, NULL, NULL, NULL, 'MK17-7EZ MILTON KEYNES - INGLATERRA', NULL, NULL, 'Brasil', NULL, 'active', 'bd_100'),
    ('MONICA', 'PATRICIA MASCARENHAS DIAS', 'diasmonica979@gmail.com', NULL, NULL, NULL, NULL, NULL, '0000-8047 SUÍÇA', NULL, NULL, 'Brasil', NULL, 'active', 'bd_101'),
    ('NELSON', 'DANIEL COELHO DE ALMEIDA - DR ROBERTO ALMEIDA', 'NAXAALMEIDA@HOTMAIL.COM', NULL, NULL, NULL, NULL, NULL, '0000-1205 GENEVE', NULL, NULL, 'Brasil', NULL, 'active', 'bd_102'),
    ('LUIS', 'MIGUEL MONTEIRO MARINHO (LENICE APARECIDA)', 'lenicemoura2009@hotmail.com', NULL, NULL, NULL, NULL, NULL, '4100-230 PORTO', NULL, NULL, 'Brasil', NULL, 'active', 'bd_103'),
    ('NADIA', 'ALEXANDRA GONÇALVES NEVES ROCHA - A PRONTO', 'nadiarocha358@gmail.com', NULL, NULL, NULL, NULL, NULL, '33250-000 FRANÇA', NULL, NULL, 'Brasil', NULL, 'active', 'bd_104'),
    ('LUCIA', 'ADRIANA DO CARMO COSTA SANTOS', 'ADRIANADCCS@GMAIL.COM', NULL, NULL, NULL, NULL, NULL, '2805-356 ALMADA', NULL, NULL, 'Brasil', NULL, 'active', 'bd_105'),
    ('JUCIENE', 'DA SILVA SANTOS', 'jubuffet@icloud.com', NULL, NULL, NULL, NULL, NULL, '4445-324 EMERSINDE', NULL, NULL, 'Brasil', NULL, 'active', 'bd_106'),
    ('BERENICE', 'DOS SANTOS - DRA. ALINE', 'berenicemoreira2@hotmail.com', NULL, NULL, NULL, NULL, NULL, '2415-394 LEIRIA', NULL, NULL, 'Brasil', NULL, 'active', 'bd_107'),
    ('HUGO', 'MIGUEL RODRIGUES CARDOSO', 'huggy_cardoso@hotmail.com', NULL, NULL, NULL, NULL, NULL, '4450-207 MATOSINHOS', NULL, NULL, 'Brasil', NULL, 'active', 'bd_108'),
    ('MARIA', 'GORETI CORREIA MATOS DE SOUSA', 'CCB04@HOTMAIL.COM', NULL, NULL, NULL, NULL, NULL, '0000-L-7240 BERELDANGE - LUXEMBURGO', NULL, NULL, 'Brasil', NULL, 'active', 'bd_109'),
    ('CIBELE', 'CRISTINA DE SOUZA', 'cibele-souza@outlook.pt', NULL, NULL, NULL, NULL, NULL, '400-038 PORTO', NULL, NULL, 'Brasil', NULL, 'active', 'bd_110'),
    ('RUI', 'MANUEL ESPERANÇA - DRA ALINE MARODIN', 'ruiesperanca16@gmail.com', NULL, NULL, NULL, NULL, NULL, '4050-359 PORTO', NULL, NULL, 'Brasil', NULL, 'active', 'bd_111'),
    ('JOSÉ', 'ALBERTO TEIXEIRA DELFIM - DRA ALINE MARODIN - A PRONTO', 'joseteixeira.delfim@live.com.pt', NULL, NULL, NULL, NULL, NULL, '5120-513 VALENÇA DO DOURO', NULL, NULL, 'Brasil', NULL, 'active', 'bd_112'),
    ('LUCIA', 'DE FATIMA FREIRE DA SILVA (DD 4789)', 'deborydavid20@hotmail.fr', NULL, NULL, NULL, NULL, NULL, 'L-1617-000 LUXEMBURGO', NULL, NULL, 'Brasil', NULL, 'active', 'bd_113'),
    ('MARIA', 'ISABEL PACHECO RIOS - DEFINITIVA', 'ISABELLERIOS945@GMAIL.COM', NULL, NULL, NULL, NULL, NULL, '11-100 França', NULL, NULL, 'Brasil', NULL, 'active', 'bd_114'),
    ('HUGO', 'MANUEL RIBEIRO - DRA. ALINE - DD', 'HUGOMRIBEIRO@OUTLOOK.COM', NULL, NULL, NULL, NULL, NULL, '6270-297 São Romão', NULL, NULL, 'Brasil', NULL, 'active', 'bd_115'),
    ('RAIMUNDA', 'DE FARIAS COLELLA - A PRONTO', 'kassiadefarias10@gmail.com', NULL, NULL, NULL, NULL, NULL, '1202-000 GENEVE SUIÇA', NULL, NULL, 'Brasil', NULL, 'active', 'bd_116'),
    ('KLEFERSON', 'BARBOSA BOTELHO', 'klefersonbotelho@gmail.com', NULL, NULL, NULL, NULL, NULL, '4465-153 SÃO MAMEDE DE INFESTA', NULL, NULL, 'Brasil', NULL, 'active', 'bd_117'),
    ('MARIA', 'TERESA NETO RODRIGUES TEIXEIRA', 'TERESANETOTEIXEIRA1967@GMAIL.COM', NULL, NULL, NULL, NULL, NULL, '4440-667 VALONGO', NULL, NULL, 'Brasil', NULL, 'active', 'bd_118'),
    ('MARIA', 'ROSA PINHEIRO SOARES - DR. ROBERTO - DD', 'ROBERTOMARINHA1977@GMAIL.COM', NULL, NULL, NULL, NULL, NULL, '4000-405 VILA NOVA DE GAIA', NULL, NULL, 'Brasil', NULL, 'active', 'bd_119'),
    ('ZILMA', 'GOMES REGUEIRO -  A PRONTO', 'zilmagf@hotmail.com', NULL, NULL, NULL, NULL, NULL, '1233-000 BERNEX SUIÇA', NULL, NULL, 'Brasil', NULL, 'active', 'bd_120'),
    ('CARLOS', 'MANUEL CARVALHO PINHO', 'SCPINHO2020@HOTMAIL.COM', NULL, NULL, NULL, NULL, NULL, 'SW8-2RB LONDRES - REINO UNIDO', NULL, NULL, 'Brasil', NULL, 'active', 'bd_121'),
    ('GLORIA', 'DOS ANJOS - DRA ALINE - A PRONTO PAGAMENTO - A PRONTO', NULL, NULL, NULL, NULL, NULL, NULL, '0000-1870 SUIÇA', NULL, NULL, 'Brasil', NULL, 'active', 'bd_122'),
    ('FERNANDO', 'ROBERTO CORAÇA - MARIDO DA DULCE - DD (Dra. Alice e Daiane)', 'FBIFRC@GMAIL.COM', NULL, NULL, NULL, NULL, NULL, '4490-405 PÓVOA DE VARZIM', NULL, NULL, 'Brasil', NULL, 'active', 'bd_123'),
    ('PAULO', 'JORGE DE OLIVEIRA REIS - DRA DAIANE ANDRADE - A PRONTO', 'martacostareis78@hotmail.com', NULL, NULL, NULL, NULL, NULL, '0000-75116 PARIS', NULL, NULL, 'Brasil', NULL, 'active', 'bd_124'),
    ('JOSE', 'CARLOS GUERRA - DR ROBERTO ALMEIDA', 'JOSEGUERRA196060@GMAIL.COM', NULL, NULL, NULL, NULL, NULL, '3830-017 GAFANHA DE AQUÉM', NULL, NULL, 'Brasil', NULL, 'active', 'bd_125'),
    ('MANUEL', 'RICARDO DE MELO PACHECO', 'RM7352599@GMAIL.COM', NULL, NULL, NULL, NULL, NULL, '8862-000 SCHUBELBACH SUIÇA', NULL, NULL, 'Brasil', NULL, 'active', 'bd_126'),
    ('PEDRO', 'MIGUEL OLIVEIRA LEITE', 'LENKA-PEDRO@HISPEED.CH', NULL, NULL, NULL, NULL, NULL, '0000-3210 SUÍÇA', NULL, NULL, 'Brasil', NULL, 'active', 'bd_127'),
    ('PAULO', 'ARMANDO JULIO DA NOVA - DRA ALINE MARODIN', 'PAULODANOVA33@GMAIL.COM', NULL, NULL, NULL, NULL, NULL, '4490-593 PÓVOA DE VARZIM', NULL, NULL, 'Brasil', NULL, 'active', 'bd_128'),
    ('APARECIDA', 'DE FÁTIMA MARTINS TEIXEIRA (DD MARIDO 5033)', 'FATIMARANDREI013@GMAIL.COM', NULL, NULL, NULL, NULL, NULL, '13200-000 ARLES FRANCE', NULL, NULL, 'Brasil', NULL, 'active', 'bd_129'),
    ('IRANILDA', 'DE FATIMA DE OLIVEIRA - DRA. ARETHUZA LUNA (BEATRIZ DE OLIVEIRA)', 'OLIVEIRA IRANILDA365@GMAIL.COM', NULL, NULL, NULL, NULL, NULL, '1040-0 villar le terroir', NULL, NULL, 'Brasil', NULL, 'active', 'bd_130'),
    ('CRISTIANO', 'ANTÓNIO AZEVEDO', 'CRISTIANO.AZEVEDO@OUTLOOK.FR', NULL, NULL, NULL, NULL, NULL, '453-40 CHAMBON LA FORÊT - FRANÇA', NULL, NULL, 'Brasil', NULL, 'active', 'bd_131'),
    ('PEDRO', 'MIGUEL PAIVA LOUREIRO - DRA. ALINE MARODIN', 'PEDROLOUREIRO1986@HOTMAIL.COM', NULL, NULL, NULL, NULL, NULL, '3530-063 MANGUALDE', NULL, NULL, 'Brasil', NULL, 'active', 'bd_132'),
    ('FERNANDO', 'DA FONSECA FERREIRA - DRA. ALINE MARODIN', 'TRABALHADOR122@GMAIL.COM', NULL, NULL, NULL, NULL, NULL, '4475-230 MAIA', NULL, NULL, 'Brasil', NULL, 'active', 'bd_133'),
    ('ARMANDO', 'DOS SANTOS VEIGA', 'ARMANDOVEIGA67@GMAIL.COM', NULL, NULL, NULL, NULL, NULL, '1815-000 CLARENS - SUIÇA', NULL, NULL, 'Brasil', NULL, 'active', 'bd_134'),
    ('SANDRA', 'MARIA PINTO MATOS', 'SADRAMM34@GMAIL.COM', NULL, NULL, NULL, NULL, NULL, '4400-360 VILA NOVA DE GAIA', NULL, NULL, 'Brasil', NULL, 'active', 'bd_135'),
    ('ANA', 'CAROLINE MURATT', 'anammuratt22@gmail.com', NULL, NULL, NULL, NULL, NULL, '4400-265 VILA NOVA DE GAIA', NULL, NULL, 'Brasil', NULL, 'active', 'bd_136'),
    ('TIAGO', 'FILIPE PEREIRA DA SILVA', 'tiago.lipe.83@gmail.com', NULL, NULL, NULL, NULL, NULL, '87-12 STAFA - SUIÇA', NULL, NULL, 'Brasil', NULL, 'active', 'bd_137'),
    ('PAULO', 'JORGE DA CRUZ ANDRADE', 'dacruzpaulo1977@gmail.com', NULL, NULL, NULL, NULL, NULL, '33-27 CRAUTHEM - LUXEMBURGO', NULL, NULL, 'Brasil', NULL, 'active', 'bd_138'),
    ('JOÃO', 'MIGUEL COELHO ANDRADE', 'andrade.design@hotmail.com', NULL, NULL, NULL, NULL, NULL, '4780-300 LAMA', NULL, NULL, 'Brasil', NULL, 'active', 'bd_139'),
    ('BRUNO', 'MIGUEL LOPES DA SILVA', 'BRUNOO20_SILVA@HOTMAIL.COM', NULL, NULL, NULL, NULL, NULL, '4080-000 LUXEMBURGO', NULL, NULL, 'Brasil', NULL, 'active', 'bd_140'),
    ('KATIA', 'MARIA DA SILVA CAMPELO', 'aindacampelokatia@gmail.com', NULL, NULL, NULL, NULL, NULL, '3130-429 QUEITIDE', NULL, NULL, 'Brasil', NULL, 'active', 'bd_141'),
    ('NEUSA', 'MARIA DE CASTRO SEBASTIAO', 'neusamorgado8@gmail.com', NULL, NULL, NULL, NULL, NULL, '6000-280 CASTELO BRANCO', NULL, NULL, 'Brasil', NULL, 'active', 'bd_142'),
    ('SANDRO', 'JOSÉ BENTO RICARDO (4779) - WISE', 'abel.almeida@hotmail.co.uk', NULL, NULL, NULL, NULL, NULL, '0000-SO168BS INGLATERRA', NULL, NULL, 'Brasil', NULL, 'active', 'bd_143'),
    ('PATRICIA', 'FRAGA MARTINS - DEFINITIVA', 'fragamartinsp@gmail.com', NULL, NULL, NULL, NULL, NULL, '69290-000 SAINT GENIS LES OLLIERES - FRANÇA', NULL, NULL, 'Brasil', NULL, 'active', 'bd_144'),
    ('ALEXANDRA', 'PAULA MARIANI PEREIRA', 'alexandramariani50@gmail.com', NULL, NULL, NULL, NULL, NULL, '4300-271 PORTO', NULL, NULL, 'Brasil', NULL, 'active', 'bd_145'),
    ('JOAQUIM', 'ANTONIO LEAL MARTINS', NULL, NULL, NULL, NULL, NULL, NULL, '6230-810 MATA DA RAINHA', NULL, NULL, 'Brasil', NULL, 'active', 'bd_146'),
    ('ROSILENE', 'LIPARI', 'liparimiranda@gmail.com', NULL, NULL, NULL, NULL, NULL, '8304-000 WALLISELLEN - SUIÇA', NULL, NULL, 'Brasil', NULL, 'active', 'bd_147'),
    ('MARIA', 'ISABEL MARTINS CARVALHO  - transferwise', 'kika782bisabel@hotmail.com', NULL, NULL, NULL, NULL, NULL, 'HA6-2PR REINO UNIDO', NULL, NULL, 'Brasil', NULL, 'active', 'bd_148'),
    ('CARMEN', 'PAULA SOUSA NOGUEIRA', 'bebianaandrade@hotmail.com', NULL, NULL, NULL, NULL, NULL, '6200-114 COVILHÃ', NULL, NULL, 'Brasil', NULL, 'active', 'bd_149'),
    ('NELSON', 'MOISES PINTO', 'nelsomoises29@gmail.com', NULL, NULL, NULL, NULL, NULL, '8752-000 NAFELLS SUIÇA', NULL, NULL, 'Brasil', NULL, 'active', 'bd_150'),
    ('JOÃO', 'PEDRO DE SOUSA MATIAS', 'carladij2@gmail.com', NULL, NULL, NULL, NULL, NULL, '47300-000 FRANÇA', NULL, NULL, 'Brasil', NULL, 'active', 'bd_151'),
    ('ELISABETA', 'GONÇALVES CALAZ PEREIRA (pagto via t«TF 4693 - IUNUS)', 'pereiraelisabeta@gmail.com', NULL, NULL, NULL, NULL, NULL, '5400-517 CHAVES', NULL, NULL, 'Brasil', NULL, 'active', 'bd_152'),
    ('IUNUS', 'AHMED', 'iunusahmed1gmail.com', NULL, NULL, NULL, NULL, NULL, '5400-517 CHAVES', NULL, NULL, 'Brasil', NULL, 'active', 'bd_153'),
    ('JOSE', 'SOARES TUNA ANDRADE E SILVA', 'josesoarestuna1703@gmail.com', NULL, NULL, NULL, NULL, NULL, '4705-173 BRAGA', NULL, NULL, 'Brasil', NULL, 'active', 'bd_154'),
    ('LUANA', 'ALEXANDRA JESUS SILVA', 'luana.silva230801@gmail.com', NULL, NULL, NULL, NULL, NULL, '4100-225 PORTO', NULL, NULL, 'Brasil', NULL, 'active', 'bd_155'),
    ('SONIA', 'RAQUEL PEREIRA PACHECO', 'raquelsonia527@gmail.com', NULL, NULL, NULL, NULL, NULL, '38100-000 GRENOBLE - FRANÇA', NULL, NULL, 'Brasil', NULL, 'active', 'bd_156'),
    ('SAULO', 'CAMPOS DE ALMEIDA', NULL, NULL, NULL, NULL, NULL, NULL, 'V95-NCD4 IRLANDA', NULL, NULL, 'Brasil', NULL, 'active', 'bd_157'),
    ('EDNA', 'HELENA DIOGO (DD EM NOME Julia Da Conceica)', 'ednafel78@gmail.com', NULL, NULL, NULL, NULL, NULL, '104-0 villar le terroir', NULL, NULL, 'Brasil', NULL, 'active', 'bd_158'),
    ('FERNANDO', 'DA SILVA DOS SANTOS', 'nando.silva70@gmail.com', NULL, NULL, NULL, NULL, NULL, 'L-4110-000 LUXEMBURGO', NULL, NULL, 'Brasil', NULL, 'active', 'bd_159'),
    ('JOSEFINA', 'GEORGETE COSTA FONSECA MOSER', 'gfonseca60@hotmail.com', NULL, NULL, NULL, NULL, NULL, '3210-000 KERZERS - SUIÇA', NULL, NULL, 'Brasil', NULL, 'active', 'bd_160'),
    ('MARIA', 'ELIZABETE TEIXEIRA MONTEIRO DE JESUS', 'mlisajusese19963@gmail.com', NULL, NULL, NULL, NULL, NULL, '4425-096 MAIA', NULL, NULL, 'Brasil', NULL, 'active', 'bd_161'),
    ('ORDEAN', 'CORRÊA DE MORAIS ANDRADE', 'ocmorais@hotmail.com', NULL, NULL, NULL, NULL, NULL, '3080-603 TAVAREDE - FIGUEIRA DA FOZ', NULL, NULL, 'Brasil', NULL, 'active', 'bd_162'),
    ('JOZIANE', 'BARROS GOMES', 'JOZY_BONY@HOTMAIL.COM', NULL, NULL, NULL, NULL, NULL, '74-270 FRANGY - FRANÇA', NULL, NULL, 'Brasil', NULL, 'active', 'bd_163'),
    ('JOCIENE', 'MELO DE OLIVEIRA (DD EM 4832 DIAMANTINO)', 'JOCIENEMELODEOLIVEIRA@GMAIL.COM', NULL, NULL, NULL, NULL, NULL, '78290-000 FRANÇA', NULL, NULL, 'Brasil', NULL, 'active', 'bd_164'),
    ('DIAMANTINO', 'TEIXEIRA AMORIM', 'jocienemelodeoliveira@gmail.com', NULL, NULL, NULL, NULL, NULL, '78290-000 FRANÇA', NULL, NULL, 'Brasil', NULL, 'active', 'bd_165'),
    ('LUCINEIDE', 'PEREIRA DA SILVA', 'luci.silva31@hotmail.com', NULL, NULL, NULL, NULL, NULL, '4420-488 VALBOM', NULL, NULL, 'Brasil', NULL, 'active', 'bd_166'),
    ('PEDRO', 'MIGUEL RIBEIRO DA FONTE', 'luciafonte80@gmail.com', NULL, NULL, NULL, NULL, NULL, '78-300 POISSY - FRANÇA', NULL, NULL, 'Brasil', NULL, 'active', 'bd_167'),
    ('ANDRÉ', 'FILIPE GUERRA DANTAS', 'andredantasr2@gmail.com', NULL, NULL, NULL, NULL, NULL, 'PAYERNE - SUIÇA', NULL, NULL, 'Brasil', NULL, 'active', 'bd_168'),
    ('SANDRA', 'ISABEL DANTAS', 'xanyasigl@gmail.com', NULL, NULL, NULL, NULL, NULL, '15-30 PAYERNE / SUIÇA', NULL, NULL, 'Brasil', NULL, 'active', 'bd_169'),
    ('INES', 'DA SILVA LUCAS - A PRONTO', 'ines.lucas1972@gmail.com', NULL, NULL, NULL, NULL, NULL, '4050-145 PORTO', NULL, NULL, 'Brasil', NULL, 'active', 'bd_170'),
    ('JOSÉ', 'MIGUEL TEIXEIRA DA SILVA', 'miguel.t.silva@hotmail.com', NULL, NULL, NULL, NULL, NULL, 'IP27-0EE ENGLAND', NULL, NULL, 'Brasil', NULL, 'active', 'bd_171'),
    ('HELEN', 'TALITA SEPULCHRO TREVISAN (BRUNO MANUEL FERREIRA DA SILVA)', 'BODHIBYHELEN@GMAIL.COM', NULL, NULL, NULL, NULL, NULL, '3880-223 OVAR', NULL, NULL, 'Brasil', NULL, 'active', 'bd_172'),
    ('ALINE', 'DA SILVA MULER', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Brasil', NULL, 'active', 'bd_173'),
    ('VALTER', 'FELIX  SANTOS', 'valter.felix.santos@gmail.com', NULL, NULL, NULL, NULL, NULL, '4480-719 VILA DO CONDE', NULL, NULL, 'Brasil', NULL, 'active', 'bd_174'),
    ('EDITE', 'SOFIA TAVARES DOS SANTOS', 'santoseditesofia@gmail.com', NULL, NULL, NULL, NULL, NULL, '41462-000 NEUSS ALEMANHA', NULL, NULL, 'Brasil', NULL, 'active', 'bd_175'),
    ('AMELIA', 'MARIA FRANCISCO', 'ameliafrancisco0103@gmail.com', NULL, NULL, NULL, NULL, NULL, 'NE6-2EZ NEWCASTLE UPON-TYNE', NULL, NULL, 'Brasil', NULL, 'active', 'bd_176'),
    ('IMARA', 'DA SILVA (depósito como cc RIES DA SILVA CHA)', 'IMARA100@HOTMAIL.COM', NULL, NULL, NULL, NULL, NULL, '91-80 OBERFEULEN - LUXEMBURGO', NULL, NULL, 'Brasil', NULL, 'active', 'bd_177'),
    ('MARIA', 'OLINDA DE BARROS DUBUGNO', 'olinda_dubugnon@hotmail.sh', NULL, NULL, NULL, NULL, NULL, '1844-000 SUIÇA', NULL, NULL, 'Brasil', NULL, 'active', 'bd_178'),
    ('MANUEL', 'SÉRGIO MACEDO - DD EM NOME DE JULIA ROSA MENDES (5408)', 'manuelsf.macedo@gmail.com', NULL, NULL, NULL, NULL, NULL, '45-430 MARDIE', NULL, NULL, 'Brasil', NULL, 'active', 'bd_179'),
    ('ANDREA', 'BEZERRA DA SILVA', 'FAYTNA@HOTMAIL.IT', NULL, NULL, NULL, NULL, NULL, '390-49 BOLZANO - ITALIA', NULL, NULL, 'Brasil', NULL, 'active', 'bd_180'),
    ('AMAIA', 'PINTO GONÇALVES', 'amayagoncalves@gmail.com', NULL, NULL, NULL, NULL, NULL, '33-470 GUJAN-MESTRAS - FRANÇA', NULL, NULL, 'Brasil', NULL, 'active', 'bd_181'),
    ('DÉBORA', 'PINTO MAFRA RIBEIRO', 'DEBORAMAFRA12@GMAIL.COM', NULL, NULL, NULL, NULL, NULL, '4200-191 PORTO', NULL, NULL, 'Brasil', NULL, 'active', 'bd_182'),
    ('ELAINE', 'BARRETO DE MORAES', 'de.elainemoraes@gmail.com', NULL, NULL, NULL, NULL, NULL, '4150-314 PORTO', NULL, NULL, 'Brasil', NULL, 'active', 'bd_183'),
    ('DUCICLEIDE', 'MOREIRA DA CUNHA DE ARAÚJO', 'DUCECLEIDEARAUJO@GMAIL.COM', NULL, NULL, NULL, NULL, NULL, '1950-00 SION - SUIÇA', NULL, NULL, 'Brasil', NULL, 'active', 'bd_184'),
    ('ANGELA', 'MENDES VARELA', 'ANGELA.RIDNEY.BRY@GMAIL.COM', NULL, NULL, NULL, NULL, NULL, '48-14 RODANGE - LUXEMBURGO', NULL, NULL, 'Brasil', NULL, 'active', 'bd_185'),
    ('ZULMIRA', 'DA CONCEIÇÃO PINHEIRO DE OLIVEIRA', 'zoliveira1671@gmail.com', NULL, NULL, NULL, NULL, NULL, '5465-0 SAULNES', NULL, NULL, 'Brasil', NULL, 'active', 'bd_186'),
    ('JOSÉ', 'MARCELO DA SILVA NOGUEIRA - A PRONTO', 'nmarceluh@gmail.com', NULL, NULL, NULL, NULL, NULL, '4560-123 PENAFIEL', NULL, NULL, 'Brasil', NULL, 'active', 'bd_187'),
    ('DULCE', 'MARIA SOARES RAMOS DE SOUSA', 'dulceramos237@gmail.com', NULL, NULL, NULL, NULL, NULL, 'L-4071 ESCH-SUR-ALZETTE/LUXEMBOURG', NULL, NULL, 'Brasil', NULL, 'active', 'bd_188'),
    ('CESALTINA', 'NEVES MOREIRA', 'pincesa45@hotmail.com', NULL, NULL, NULL, NULL, NULL, '57-710 AUMETZ FRANÇA', NULL, NULL, 'Brasil', NULL, 'active', 'bd_189'),
    ('EMERSON', 'LIMA HORST', 'emerson.horst@hotmail.fr', NULL, NULL, NULL, NULL, NULL, '84-860 CADEROUSSE - FRANÇA', NULL, NULL, 'Brasil', NULL, 'active', 'bd_190'),
    ('BRUNO', 'MANUEL FERREIRA SILVA SANTOS', 'bruno.santos@hotmail.fr', NULL, NULL, NULL, NULL, NULL, '83420-00 LA CROIX VALMEN - FRANÇA', NULL, NULL, 'Brasil', NULL, 'active', 'bd_191'),
    ('PAULO', 'RICARDO GONÇALVES DA SILVA - TEM DESCONTO MUTUALISTA', 'paulogrsilva88@gmail.com', NULL, NULL, NULL, NULL, NULL, '6185-461 VILARINHO', NULL, NULL, 'Brasil', NULL, 'active', 'bd_192'),
    ('JEFFERSON', 'FAGUNDES DE SOUZA', 'adonai05@hotmail.com', NULL, NULL, NULL, NULL, NULL, 'SW19-6EX LONDRES', NULL, NULL, 'Brasil', NULL, 'active', 'bd_193'),
    ('JOÃO', 'JOSÉ FERREIRA DIAS', 'dealmeida1985@hotmail.com', NULL, NULL, NULL, NULL, NULL, '4430-518 VILA NOVA DE GAIA', NULL, NULL, 'Brasil', NULL, 'active', 'bd_194'),
    ('MIGUEL', 'FERNANDO DOS SANTOS LOUREIRO DA SILVA', 'MIGUELSILVA75@GMAIL.COM', NULL, NULL, NULL, NULL, NULL, '4400-367 VILA NOVA DE GAIA', NULL, NULL, 'Brasil', NULL, 'active', 'bd_195'),
    ('PAULA', 'CRISTINA PINTO MOREIRA', 'pcpmoreira@gmail.com', NULL, NULL, NULL, NULL, NULL, '4400-367 VILA NOVA DE GAIA', NULL, NULL, 'Brasil', NULL, 'active', 'bd_196'),
    ('SÍLVIA', 'ANDREIA ALVES SILVA OLIVEIRA', 'SILVYANDREIA@HOTMAIL.COM', NULL, NULL, NULL, NULL, NULL, '388-00 LE PONT DE CLAIX - FRANÇA', NULL, NULL, 'Brasil', NULL, 'active', 'bd_197'),
    ('VITOR', 'MANUEL DOS PRAZERES CECILIO', 'ANABELA1982@HOTMAIL.CEO.UK', NULL, NULL, NULL, NULL, NULL, 'LONDRES', NULL, NULL, 'Brasil', NULL, 'active', 'bd_198'),
    ('IRENE', 'DA SILVA SANTOS DIAS', 'irene_56_@hotmail.com', NULL, NULL, NULL, NULL, NULL, '10-26 DENGES/SUISSE', NULL, NULL, 'Brasil', NULL, 'active', 'bd_199'),
    ('M''BOMBA', 'TCHUDA -- COROAS', 'EVILAZIO84@GMAIL.COM', NULL, NULL, NULL, NULL, NULL, '2580-601 CARREGADO - PORTUGAL', NULL, NULL, 'Brasil', NULL, 'active', 'bd_200'),
    ('RAQUEL', 'CUNHA DOS SANTOS MOREIRA (DD EM NOME DO MARIDO 5265)', 'raquel33santosmoreira@gmail.com', NULL, NULL, NULL, NULL, NULL, '4560-124 GALEGOS', NULL, NULL, 'Brasil', NULL, 'active', 'bd_201'),
    ('ALEXANDRE', 'CABRAL DA SILVA', 'SUMIGACS@YAHOO.COM.BR', NULL, NULL, NULL, NULL, NULL, '4435-191 RIO TINTO', NULL, NULL, 'Brasil', NULL, 'active', 'bd_202'),
    ('LUAN', 'VINICIUS GONÇALVES VIEIRA', 'luan_vgv@hotmail.com', NULL, NULL, NULL, NULL, NULL, '5430-461 VALPAÇOS', NULL, NULL, 'Brasil', NULL, 'active', 'bd_203'),
    ('PAULO', 'HENRIQUE DE JESUS', 'PAULINHOMARCANTE@GMAIL.COM', NULL, NULL, NULL, NULL, NULL, 'BS9-2JQ BRISTOL - INGLATERRA', NULL, NULL, 'Brasil', NULL, 'active', 'bd_204'),
    ('LUIS', 'ANTONIO MADEIRA PAIS', 'madeirapais7@gmail.com', NULL, NULL, NULL, NULL, NULL, '39-11 RIED-BRIG / SUIÇA', NULL, NULL, 'Brasil', NULL, 'active', 'bd_205'),
    ('ROSA', 'CRISTINA SILVA DIAS', 'CRIS.SDR.13@HOTMAIL.COM', NULL, NULL, NULL, NULL, NULL, 'F544-00 LONGWY - FRANÇA', NULL, NULL, 'Brasil', NULL, 'active', 'bd_206'),
    ('TATIANA', 'MESSIAS DOS SANTOS', 'TATIANAMESS@HOTMAIL.COM', NULL, NULL, NULL, NULL, NULL, '95-000 CERGY - FRANÇA', NULL, NULL, 'Brasil', NULL, 'active', 'bd_207'),
    ('BRUNO', 'MIGUEL MENDES DOS SANTOS (IDENTIFICADO SOB - TRF PINHO TEIXEIRA F)', 'brunosantos_600@hotmail.com', NULL, NULL, NULL, NULL, NULL, '12-03 GENÊVE - SUIÇA', NULL, NULL, 'Brasil', NULL, 'active', 'bd_208'),
    ('ANTONIO', 'LUIS FERREIRA NUNES', 'NUNESLUIS1971@GMAIL.COM', NULL, NULL, NULL, NULL, NULL, '4585-607 RECREIO /PAREDES', NULL, NULL, 'Brasil', NULL, 'active', 'bd_209'),
    ('VALENTINA', 'ANTONELA SANHUEZA VARGAS', NULL, NULL, NULL, NULL, NULL, NULL, '4150-638 PORTO', NULL, NULL, 'Brasil', NULL, 'active', 'bd_210'),
    ('MARCIA', 'SANTANA DIAS', 'marcia_diassantana@hotmail.com', NULL, NULL, NULL, NULL, NULL, '4250-377 FRANCOS - PORTO', NULL, NULL, 'Brasil', NULL, 'active', 'bd_211'),
    ('CRISTINA', 'MARIA DA SILVA FERREIRA', 'crishugoandre02@gmail.com', NULL, NULL, NULL, NULL, NULL, '4100-202 PORTO', NULL, NULL, 'Brasil', NULL, 'active', 'bd_212'),
    ('SAIONARA', 'DANTAS LOPES', 'sayolopes2025@hotmail.com', NULL, NULL, NULL, NULL, NULL, '2765-459 SÃO JOÃO DO ESTORIL', NULL, NULL, 'Brasil', NULL, 'active', 'bd_213'),
    ('CRISTINA', 'MARIA DE SOUSA PEREIRA DAVID', 'cpereira_1975@hotmail.com', NULL, NULL, NULL, NULL, NULL, '4450-137 MATOSINHOS', NULL, NULL, 'Brasil', NULL, 'active', 'bd_214'),
    ('GUSTAVO', 'DIAS BINS', 'binsgustavo@gmail.com', NULL, NULL, NULL, NULL, NULL, '77-340 PONTAULT-COMBAULT / FRANÇA', NULL, NULL, 'Brasil', NULL, 'active', 'bd_215'),
    ('CARLOS', 'GERMANO', 'glaucialopesgermano@gmail.com', NULL, NULL, NULL, NULL, NULL, '3730-255 VALE DE CAMBRA', NULL, NULL, 'Brasil', NULL, 'active', 'bd_216'),
    ('VITOR', 'MANUEL FERREIRA DIAS', 'mmgd33@hotmail.com', NULL, NULL, NULL, NULL, NULL, '4430-629 VILA NOVA DE GAIA', NULL, NULL, 'Brasil', NULL, 'active', 'bd_217'),
    ('ALAN', 'CARLOS ALFREDO', 'ALAN060486@HOTMAIL.COM', NULL, NULL, NULL, NULL, NULL, 'SW19-6PP LONDRES', NULL, NULL, 'Brasil', NULL, 'active', 'bd_218'),
    ('MANUELA', 'DOS SANTOS REGO VASCONCELOS', 'manuela.vasco2017@gmail.com', NULL, NULL, NULL, NULL, NULL, '4150-427 PORTO', NULL, NULL, 'Brasil', NULL, 'active', 'bd_219'),
    ('BETITZA', 'RAMONA CORAGGIO - DD EM NOME DO FILHO PEDRO ENRRIQUE GALLARDO CARPIO (DD NO 5401)', 'pedro.gallardo.c@gmail.com', NULL, NULL, NULL, NULL, NULL, '4710-409 SÃO VICTOR / BRAGA', NULL, NULL, 'Brasil', NULL, 'active', 'bd_220'),
    ('MARLI', 'RODRIGUES DE BARROS THURING', 'rodriguesmarli1962@gmail.com', NULL, NULL, NULL, NULL, NULL, '40-58 BASEL - SUIÇA', NULL, NULL, 'Brasil', NULL, 'active', 'bd_221'),
    ('SANDRA', 'PATRÍCIA MARINHO DE SOUSA', 'spcpatriciamarinho@gmail.com', NULL, NULL, NULL, NULL, NULL, '40-57 BASEL - SUIÇA', NULL, NULL, 'Brasil', NULL, 'active', 'bd_222'),
    ('PAULO', 'ROBERTO ARCANJO RIBEIRO', 'arcanjopaulo208@hotmail.com', NULL, NULL, NULL, NULL, NULL, '4100-128 PORTO', NULL, NULL, 'Brasil', NULL, 'active', 'bd_223'),
    ('ALEXANDRE', 'ANTUNES PEREIRA VICENTE', 'alexandrevicentecomandos@gmail.com', NULL, NULL, NULL, NULL, NULL, '4440-777 VALONGO', NULL, NULL, 'Brasil', NULL, 'active', 'bd_224'),
    ('RAMON', 'CAIO VIANA BRAGA', 'ramon.caio@hotmail.com', NULL, NULL, NULL, NULL, NULL, '4000-057 PORTO', NULL, NULL, 'Brasil', NULL, 'active', 'bd_225'),
    ('MARIA', 'HELENA AFONSO - ESPOSO ANTONIO RIBEIRO AFONSO (SWISS)', 'NAO POSSUI', NULL, NULL, NULL, NULL, NULL, '40-55 BASEL - SUIÇA', NULL, NULL, 'Brasil', NULL, 'active', 'bd_226'),
    ('HELDER', 'VICENTE DA SILVA SANTOS', 'GENEVE.HS@GMAIL.COM', NULL, NULL, NULL, NULL, NULL, '3850-364 ALBERGARIA VELHA', NULL, NULL, 'Brasil', NULL, 'active', 'bd_227'),
    ('ALEX', 'BATISTA CORREA', 'alexbatistacorrea89@gmail.com', NULL, NULL, NULL, NULL, NULL, '93-380 PIERREFITTE-SUR-SEINE / FRANÇA', NULL, NULL, 'Brasil', NULL, 'active', 'bd_228'),
    ('TIAGO', 'EMANUEL LIMA', 'limatiagocre@gmail.com', NULL, NULL, NULL, NULL, NULL, 'E152-PZ LONDRES', NULL, NULL, 'Brasil', NULL, 'active', 'bd_229'),
    ('MANUELLIZCHA', 'DA SILVA MARQUES SHCHERBAKOV', 'sh.vitaliy@gmail.com', NULL, NULL, NULL, NULL, NULL, '821-2 NEUHAUSEN AM RHEINFALL', NULL, NULL, 'Brasil', NULL, 'active', 'bd_230'),
    ('RONALDO', 'SILVA SOUSA', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Brasil', NULL, 'active', 'bd_231'),
    ('BRUNO', 'CASTRO ARAUJO', 'araujobc7821@gmail.com', NULL, NULL, NULL, NULL, NULL, 'VILA DO CONDE - PORTUGAL', NULL, NULL, 'Brasil', NULL, 'active', 'bd_232'),
    ('MARINA', 'ISABEL DE OLIVEIRA SIMÃOZINHO', NULL, NULL, NULL, NULL, NULL, NULL, '0645-0 RODUEBILLIERE - FRANÇA', NULL, NULL, 'Brasil', NULL, 'active', 'bd_233'),
    ('MARIA', 'APARECIDA ALVES', 'peniel-2011@live.com', NULL, NULL, NULL, NULL, NULL, '67-91 ATHUS/ALBANGE - BELGICA', NULL, NULL, 'Brasil', NULL, 'active', 'bd_234'),
    ('ANTONIO', 'CARLOS DOS SANTOS', NULL, NULL, NULL, NULL, NULL, NULL, '67-91 ATHUS/ALBANGE - BELGICA', NULL, NULL, 'Brasil', NULL, 'active', 'bd_235'),
    ('CRISTIANO', 'BATISTA DE OLIVEIRA', 'agulha.portuga@gmx.com.uk', NULL, NULL, NULL, NULL, NULL, 'n17-0hx London', NULL, NULL, 'Brasil', NULL, 'active', 'bd_236'),
    ('ANA', 'CAROLINA SANTARELLI', 'ANACAROLSANTARELLI@ICLOUD.COM', NULL, NULL, NULL, NULL, NULL, '4350-109 ANTAS - PORTO', NULL, NULL, 'Brasil', NULL, 'active', 'bd_237'),
    ('ALCINDA', 'MARIA ANDRADE DOS SANTOS', 'alcinda6bruxelas@gmail.com', NULL, NULL, NULL, NULL, NULL, '710-0 La louviere - Belgique', NULL, NULL, 'Brasil', NULL, 'active', 'bd_238'),
    ('BERNO', 'VENANZIO DANIELE', 'info@clubcafe-kerzers.ch', NULL, NULL, NULL, NULL, NULL, '32-10 KERZERS', NULL, NULL, 'Brasil', NULL, 'active', 'bd_239'),
    ('SONIA', 'MARIA DE FREITAS', 'sonykida@hotmail.com', NULL, NULL, NULL, NULL, NULL, '9300-060 CÂMARA DE LOBOS', NULL, NULL, 'Brasil', NULL, 'active', 'bd_240'),
    ('MARIA', 'FERNANDA MARTINS BERNARDO', 'mfernandabernardo49@gmail.com', NULL, NULL, NULL, NULL, NULL, 'Bellach - Solo Turn', NULL, NULL, 'Brasil', NULL, 'active', 'bd_241'),
    ('PAULA', 'MARGARIDA GOMES TAVARES PEREIRA', 'FRMTAVARES70@GMAIL.COM', NULL, NULL, NULL, NULL, NULL, '405-7 SUIÇA', NULL, NULL, 'Brasil', NULL, 'active', 'bd_242'),
    ('MONIO', 'JOSÉ BARBOSA', 'paifilho44@hotmail.com', NULL, NULL, NULL, NULL, NULL, '15-00 HALLE - BÉLGICA', NULL, NULL, 'Brasil', NULL, 'active', 'bd_243'),
    ('JAQUELINE', 'DE OLIVEIRA CLAUDINO MAUDET', 'mjackie50.mj@gmail.com', NULL, NULL, NULL, NULL, NULL, '95-310 SAINT OUEN LAUMONE - FRANCE', NULL, NULL, 'Brasil', NULL, 'active', 'bd_244'),
    ('JOSE', 'DIOGO RIBEIRO DA COSTA', 'barbarasolange92@gmail.com', NULL, NULL, NULL, NULL, NULL, '4585-893 SOBREIRA - PAREDES', NULL, NULL, 'Brasil', NULL, 'active', 'bd_245'),
    ('SANDRA', 'ISABEL PEREIRA AMORIM PINHEIRO', 'martinspinheiro1@hotmail.com', NULL, NULL, NULL, NULL, NULL, '81-800 COUFOULEUX - FRANÇA', NULL, NULL, 'Brasil', NULL, 'active', 'bd_246'),
    ('SANDRA', 'LUCIA SCHNEUWLY', 'sandyswisse36@gmail.com', NULL, NULL, NULL, NULL, NULL, '10-12 LAUSANNE - SUIÇA', NULL, NULL, 'Brasil', NULL, 'active', 'bd_247'),
    ('MARINA', 'GONZAGA DA COSTA', 'marinagonzagadacosta@gmail.com', NULL, NULL, NULL, NULL, NULL, '4435-318 rio tinto-gondomar', NULL, NULL, 'Brasil', NULL, 'active', 'bd_248'),
    ('DALILA', 'CRISTINA DA COSTA AZEVEDO', 'dacostadalila@hotmail.com', NULL, NULL, NULL, NULL, NULL, '15-30 PAYERNE - SUIÇA', NULL, NULL, 'Brasil', NULL, 'active', 'bd_249'),
    ('MARIA', 'JOSÉ AMARAL', 'belarminoferreiramsn.com', NULL, NULL, NULL, NULL, NULL, '800-8 ZURICH', NULL, NULL, 'Brasil', NULL, 'active', 'bd_250'),
    ('ANA', 'CLAUDIA CASEIRO VILAS BOAS', 'anavilasboas@msn.com', NULL, NULL, NULL, NULL, NULL, '8952-000 SCHLIETEN - SUIÇA', NULL, NULL, 'Brasil', NULL, 'active', 'bd_251'),
    ('MARIA', 'FERNANDA MONTEIRO', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Brasil', NULL, 'active', 'bd_252'),
    ('CARLA', 'PATRÍCIA VIEIRA DE LEMOS', 'cpatriciavlemos@gmail.com', NULL, NULL, NULL, NULL, NULL, '4400-267 VILA NOVA DE GAIA', NULL, NULL, 'Brasil', NULL, 'active', 'bd_253'),
    ('DANIEL', 'MOTA CARVALHO', 'daniel@overlay.pt', NULL, NULL, NULL, NULL, NULL, '2005-455 SANTARÉM', NULL, NULL, 'Brasil', NULL, 'active', 'bd_254'),
    ('MARLI', 'JACINTA KOLODZIEJSKI COELHO', 'marlikol15@hotmail.com', NULL, NULL, NULL, NULL, NULL, '4520-215 SANTA MARIA DA FEIRA', NULL, NULL, 'Brasil', NULL, 'active', 'bd_255'),
    ('RAFAEL', 'NABAIS PEDRICO', 'rafaelpedrico@hotmail.com', NULL, NULL, NULL, NULL, NULL, '6320-371 SABUGAL', NULL, NULL, 'Brasil', NULL, 'active', 'bd_256'),
    ('TANIA', 'MONTEIRO DA SILVA CANDEIAS (6066 JOÃO CANDEIAS)', NULL, NULL, NULL, NULL, NULL, NULL, '88-20 TORHOUT - BÉLGICA', NULL, NULL, 'Brasil', NULL, 'active', 'bd_257'),
    ('MICHELLE', 'MORAIS DE BARROS WEDER', 'mimi.weder@gmail.com', NULL, NULL, NULL, NULL, NULL, '10-18 LAUSANNE', NULL, NULL, 'Brasil', NULL, 'active', 'bd_258'),
    ('RICARDO', 'JOSÉ LOPES MAGALHÃES GONÇALVES', 'ricardomagalhaes@hotmail.ch', NULL, NULL, NULL, NULL, NULL, '68-300 FRANÇA', NULL, NULL, 'Brasil', NULL, 'active', 'bd_259'),
    ('MARIA', 'ALICE DA COSTA ARRUELA', 'arruelalice@gmail.com', NULL, NULL, NULL, NULL, NULL, '4400-603 VILA NOVA DE GAIA', NULL, NULL, 'Brasil', NULL, 'active', 'bd_260'),
    ('MARIA', 'JOSÉ GOMES DOS SANTOS', 'pedromonteiroaluno@gmail.com', NULL, NULL, NULL, NULL, NULL, '4400-350 VILA NOVA DE GAIA', NULL, NULL, 'Brasil', NULL, 'active', 'bd_261'),
    ('GABRIEL', 'DA SILVA LINS', 'gabrielslv1950@gmail.com', NULL, NULL, NULL, NULL, NULL, '129-3 Geneve', NULL, NULL, 'Brasil', NULL, 'active', 'bd_262'),
    ('VITALY', 'VASYLYOVYSCH SHCHERBAKOV', 'sh.vitaliy@gmail.com', NULL, NULL, NULL, NULL, NULL, '82-12 NEUHAUSEM AM RHEINFALL', NULL, NULL, 'Brasil', NULL, 'active', 'bd_263'),
    ('SUSANA', 'MARIA DA SILVA RIBEIRO CASTRO', 'susanacastro7473@gmail.com', NULL, NULL, NULL, NULL, NULL, '12-03 GENEVE - SUIÇA', NULL, NULL, 'Brasil', NULL, 'active', 'bd_264'),
    ('JOSÉ', 'MANUEL TEIXEIRA DE SOUSA', 'MANUELCD091@GMAIL.COM', NULL, NULL, NULL, NULL, NULL, '4625-030 ARIZ', NULL, NULL, 'Brasil', NULL, 'active', 'bd_265'),
    ('ALBERTO', 'FERNANDO PINHO', 'ALBERTOFPCOSTA@HOTMAIL.COM', NULL, NULL, NULL, NULL, NULL, '4400-350 VILA NOVA DE GAIA', NULL, NULL, 'Brasil', NULL, 'active', 'bd_266'),
    ('PEDRO', 'MANUEL FERREIRA DA SILVA', 'PEDROFERREIRA715@GMAIL.COM', NULL, NULL, NULL, NULL, NULL, '185-7 BERTRANGE', NULL, NULL, 'Brasil', NULL, 'active', 'bd_267'),
    ('JULIA', 'CRISTINA ALMEIDA SOARES', 'juliacasoares@gmail.com', NULL, NULL, NULL, NULL, NULL, '30-01 HEVERLEE - BÉLGICA', NULL, NULL, 'Brasil', NULL, 'active', 'bd_268'),
    ('ADELAIDE', 'MARIA LOPES MILHAZES', 'torcatofcp@hotmail.com', NULL, NULL, NULL, NULL, NULL, 'VILA DO CONDE', NULL, NULL, 'Brasil', NULL, 'active', 'bd_269'),
    ('ROSA', 'CRISTINA FARINHA MARTINS', 'rosacristinamartins2019@gmail.com', NULL, NULL, NULL, NULL, NULL, '6100-775 SERTÃ', NULL, NULL, 'Brasil', NULL, 'active', 'bd_270'),
    ('DINA', 'PAULA MONIZ VIEIRA (LETICIA FATIMA MO)', 'dinamoniz27@gmail.com', NULL, NULL, NULL, NULL, NULL, 'ONL6A-2R2 MAPLE - CANADA', NULL, NULL, 'Brasil', NULL, 'active', 'bd_271'),
    ('RENATA', 'RODRIGUES DA SILVA', 'paifilho44@hotmail.com', NULL, NULL, NULL, NULL, NULL, '15-00 HALLE - BÉLGICA', NULL, NULL, 'Brasil', NULL, 'active', 'bd_272'),
    ('ANTÓNIO', 'GABRIEL SOUSA GUEDES', 'sousaguedes31@gmail.com', NULL, NULL, NULL, NULL, NULL, '4820-457 GOLÃES', NULL, NULL, 'Brasil', NULL, 'active', 'bd_273'),
    ('INES', 'GOMES DA COSTA', 'inescosta4400@gmail.com', NULL, NULL, NULL, NULL, NULL, '4400-350 VILA NOVA DE GAIA', NULL, NULL, 'Brasil', NULL, 'active', 'bd_274'),
    ('HUGO', 'ALEXANDRE DA COSTA TORRES', 'ugoavec1990@icloud.com', NULL, NULL, NULL, NULL, NULL, '16-90 ROMONT - SUIÇA', NULL, NULL, 'Brasil', NULL, 'active', 'bd_275'),
    ('MARIA', 'ADELIA SILVA', 'crishugoandre02@gmail.com', NULL, NULL, NULL, NULL, NULL, '4100-202 RAMALDE', NULL, NULL, 'Brasil', NULL, 'active', 'bd_276'),
    ('VITAL', 'MANUEL GONÇALVES BRÍZIDA', 'VITALBRIZIDAVITAL@GMAIL.COM', NULL, NULL, NULL, NULL, NULL, '679-0 BELGICA', NULL, NULL, 'Brasil', NULL, 'active', 'bd_277'),
    ('GISELE', 'TOBIAS MIRANDA', 'GITOBIASMIRANDA@GMAIL.COM', NULL, NULL, NULL, NULL, NULL, '4050-308 PORTO', NULL, NULL, 'Brasil', NULL, 'active', 'bd_278'),
    ('MARIA', 'HORTENSE CHORA', 'maria.hortense1959@gmail.com', NULL, NULL, NULL, NULL, NULL, '2725-391 SINTRA', NULL, NULL, 'Brasil', NULL, 'active', 'bd_279'),
    ('ANA', 'CECILIA  FUENTES', 'silvamicael08@gmail.com', NULL, NULL, NULL, NULL, NULL, '18-15 CLAREHS SUIÇA', NULL, NULL, 'Brasil', NULL, 'active', 'bd_280'),
    ('MICAEL', 'FILIPE SILVA', 'silvamicael08@gmail.com', NULL, NULL, NULL, NULL, NULL, '18-15 Suiça', NULL, NULL, 'Brasil', NULL, 'active', 'bd_281'),
    ('CÉSAR', 'DOMINGOS VAZ MORENO', 'alodovicc@hotmail.com', NULL, NULL, NULL, NULL, NULL, 'L43-60 ESCH SUR ALZETTE - LUXEMBURGO', NULL, NULL, 'Brasil', NULL, 'active', 'bd_282'),
    ('FÁTIMA', 'ESTEPHANIO DE MOURA (PAGO VIA COD 3008 - MÃE DA FERNANDA RICCIARDONE)', 'fafaestephanio@gmail.com', NULL, NULL, NULL, NULL, NULL, '4420-597 GONDOMAR', NULL, NULL, 'Brasil', NULL, 'active', 'bd_283'),
    ('MARIA', 'ANGELICA DOS SANTOS OLIVEIRA', 'mariangelicapt73@gmail.com', NULL, NULL, NULL, NULL, NULL, '7349-0 La ravoire', NULL, NULL, 'Brasil', NULL, 'active', 'bd_284'),
    ('REBECKA', 'CAIRES BRITO DE OLIVEIRA', 'cairesrebecka@gmail.com', NULL, NULL, NULL, NULL, NULL, '4595-133 FRASAO', NULL, NULL, 'Brasil', NULL, 'active', 'bd_285'),
    ('NILCE', 'DE OLIVEIRA CASTRO', 'nilcedcastro@gmail.com', NULL, NULL, NULL, NULL, NULL, '4350-172 PARANHOS PORTO', NULL, NULL, 'Brasil', NULL, 'active', 'bd_286'),
    ('JOAO', 'PEDRO RAMOS DE SOUSA', 'joaobpedrof@gmail.com', NULL, NULL, NULL, NULL, NULL, '4200-218 PORTO', NULL, NULL, 'Brasil', NULL, 'active', 'bd_287'),
    ('FERNANDA', 'DOS SANTOS OLIVEIRA LOURENÇO', NULL, NULL, NULL, NULL, NULL, NULL, '4415-252 PEDROSO', NULL, NULL, 'Brasil', NULL, 'active', 'bd_288'),
    ('PALOMA', 'MORENO', 'palomamoreno@outlook.fr', NULL, NULL, NULL, NULL, NULL, '7501-2 paris', NULL, NULL, 'Brasil', NULL, 'active', 'bd_289'),
    ('ALMIRO', 'LUÍS DA SILVA SANTOS', 'NAO POSSUI', NULL, NULL, NULL, NULL, NULL, '3720-398 CUCUJÃES - PORTUGAL', NULL, NULL, 'Brasil', NULL, 'active', 'bd_290'),
    ('ROSIMAR', 'FERREIRA REIS', 'rosimarfreis75@gmail.com', NULL, NULL, NULL, NULL, NULL, '4450-139 MATOSINHOS', NULL, NULL, 'Brasil', NULL, 'active', 'bd_291'),
    ('PEDRO', 'JAIME DAS DORES SOUSA', 'PJAIMESOUSA@HOTMAIL.COM', NULL, NULL, NULL, NULL, NULL, 'CV13-6LE NUNEATON - INGLATERRA', NULL, NULL, 'Brasil', NULL, 'active', 'bd_292'),
    ('MARIA', 'DE LURDES CARDANHA AUGUSTO', 'marieaugusto@hotmail.fr', NULL, NULL, NULL, NULL, NULL, '75-007 Paris', NULL, NULL, 'Brasil', NULL, 'active', 'bd_293'),
    ('JOSÉ', 'NGOLA MARQUES', 'JOSE.NGOLA.MARQUES@GMAIL.COM', NULL, NULL, NULL, NULL, NULL, 'PQE-15JQ PETERBOROUGH', NULL, NULL, 'Brasil', NULL, 'active', 'bd_294'),
    ('LUCIANE', 'PEREIRA DE SOUSA (Gilberto Maciel Gomes Ferreira)', 'lucianelili@gmail.com', NULL, NULL, NULL, NULL, NULL, '4760-502 GONDIFELOS - VILA NOVA DE FAMALICAO', NULL, NULL, 'Brasil', NULL, 'active', 'bd_295'),
    ('MICHEL', 'GOMES', 'michelgomes198533@gmail.com', NULL, NULL, NULL, NULL, NULL, '07-800 BEAUCHASTEL - FRANCE', NULL, NULL, 'Brasil', NULL, 'active', 'bd_296'),
    ('TIAGO', 'ANTÔNIO PINTO FARIA DE ARAÚJO', 'TI.FAR@ICLOUD.COM', NULL, NULL, NULL, NULL, NULL, '4760-705 RIBEIRÃO', NULL, NULL, 'Brasil', NULL, 'active', 'bd_297'),
    ('ELIONAI', 'NOGUEIRA', 'elionaikellyene@gmail.com', NULL, NULL, NULL, NULL, NULL, '11-50 WOLUWE-SAINT-PIERRE', NULL, NULL, 'Brasil', NULL, 'active', 'bd_298'),
    ('BRUNA', 'DANIELA DA CUNHA JESUS', 'brunah_7@hotmail.com', NULL, NULL, NULL, NULL, NULL, '4420-539 VALBOM - GONDOMAR', NULL, NULL, 'Brasil', NULL, 'active', 'bd_299'),
    ('CARINA', 'MARIA DA COSTA NOIVO ANTUNES', 'CARINANTUNES78@GMAIL.COM', NULL, NULL, NULL, NULL, NULL, '2525-412 COIMBRÃ - ATOUGUIA DA BALEIA - PENICHE', NULL, NULL, 'Brasil', NULL, 'active', 'bd_300'),
    ('CARLA', 'MARIA DIAS DE ALMEIDA', 'almeidacarla78@hotmail.com', NULL, NULL, NULL, NULL, NULL, '9141-0 DOURDAN - FRANÇA', NULL, NULL, 'Brasil', NULL, 'active', 'bd_301'),
    ('JOSÉ', 'JOAQUIM PEREIRA DA COSTA', 'JOSEJOAQUIMPEREIRACOSTA5@GMAIL.COM', NULL, NULL, NULL, NULL, NULL, '172-6 FARVAGNY-LE-GRAND', NULL, NULL, 'Brasil', NULL, 'active', 'bd_302'),
    ('ANTÔNIO', 'RISONEY LOPES', 'neybalaalice1533@gmail.com', NULL, NULL, NULL, NULL, NULL, '16-30 BULLE, FRIBURGO, SWITZRLAND', NULL, NULL, 'Brasil', NULL, 'active', 'bd_303'),
    ('MARCO', 'PAULO BENFEITAS DE PINHO', 'MARCO010383@HOTMAIL.COM', NULL, NULL, NULL, NULL, NULL, '0413-0 FRANÇA', NULL, NULL, 'Brasil', NULL, 'active', 'bd_304'),
    ('NERCÍ', 'GONÇALVES PEREIRA (DD NOME ARMANDO PEREIRA)', 'NERCIGP@HOTMAIL.COM', NULL, NULL, NULL, NULL, NULL, '95-800 CERGY - FRANÇA', NULL, NULL, 'Brasil', NULL, 'active', 'bd_305'),
    ('MARIANA', 'ISABEL MONTEIRO CARDOSO', 'ISABEL.MARIANACARDOSO1986@GMAIL.COM', NULL, NULL, NULL, NULL, NULL, '4625-417 SANDE', NULL, NULL, 'Brasil', NULL, 'active', 'bd_306'),
    ('JOSÉ', 'ANTÓNIO PEREIRA PIRES   (liliana pereira)', 'j.pires@mueller-gleisbau.ch', NULL, NULL, NULL, NULL, NULL, '850-0 Frauenfeld SUIÇA', NULL, NULL, 'Brasil', NULL, 'active', 'bd_307'),
    ('PAULO', 'JORGE LIBERATO QUINTELA', 'libquintela@hotmail.com', NULL, NULL, NULL, NULL, NULL, '101-8 Suiça', NULL, NULL, 'Brasil', NULL, 'active', 'bd_308'),
    ('IOLANDA', 'MANUELA PEIXINHO DE OLIVEIRA CARVALHO', NULL, NULL, NULL, NULL, NULL, NULL, '4510-294 SÃO PEDRO DA COVA', NULL, NULL, 'Brasil', NULL, 'active', 'bd_309'),
    ('BRUNO', 'MANUEL DE OLIVEIRA SANTOS', 'brunosantos868@gmail.com', NULL, NULL, NULL, NULL, NULL, '4525-331 GUISANDE', NULL, NULL, 'Brasil', NULL, 'active', 'bd_310'),
    ('SÉRGIO', 'BRUNO DE ALMEIDA VICÊNCIO (SOARES CARDOSO)', 'SERGIOALMEIDAVIC@GMAIL.COM', NULL, NULL, NULL, NULL, NULL, '2050-360 AZAMBUJA', NULL, NULL, 'Brasil', NULL, 'active', 'bd_311'),
    ('LUÍS', 'MANUEL RIBEIRO LOPES', 'lopes_20@hotmail.fr', NULL, NULL, NULL, NULL, NULL, '3070-021 CARROMEU', NULL, NULL, 'Brasil', NULL, 'active', 'bd_312'),
    ('DONATINA', 'BERNO', 'info@clubcafe-kerzers.ch', NULL, NULL, NULL, NULL, NULL, '32-10 KERZERS', NULL, NULL, 'Brasil', NULL, 'active', 'bd_313'),
    ('JACQUELINE', 'BORGES DE SOUSA', 'jacquesousa10@hotmail.com', NULL, NULL, NULL, NULL, NULL, '4050-435 PORTO', NULL, NULL, 'Brasil', NULL, 'active', 'bd_314'),
    ('HELDER', 'GOMES DA CRUZ', 'HELDERGOMESCRUZ@OUTLOOK.COM', NULL, NULL, NULL, NULL, NULL, '2700-526 AMADORA', NULL, NULL, 'Brasil', NULL, 'active', 'bd_315'),
    ('JOÃO', 'MANUEL DA SILVA TAVARES', 'jpunka@gmail.com', NULL, NULL, NULL, NULL, NULL, 'L-83-65 HAGEN - LUXEMBURGO', NULL, NULL, 'Brasil', NULL, 'active', 'bd_316'),
    ('MARIA', 'CATARINA PEREIRA DUARTE FERNANDES', 'MARIACATARINADUARTE071@GMAIL.COM', NULL, NULL, NULL, NULL, NULL, '16-80 ROMONT - SUIÇA', NULL, NULL, 'Brasil', NULL, 'active', 'bd_317'),
    ('PEDRO', 'RICARDO MOREIRA DOS SANTOS', 'patricia_costa88@hotmail.com', NULL, NULL, NULL, NULL, NULL, '79-320 MONCOUTANT - FRANÇA', NULL, NULL, 'Brasil', NULL, 'active', 'bd_318'),
    ('MARIA', 'RIBEIRO MARTINS', 'TIDARIBEIROMG@GMAIL.COM', NULL, NULL, NULL, NULL, NULL, 'LINDA A VELHA', NULL, NULL, 'Brasil', NULL, 'active', 'bd_319'),
    ('LUIS', 'FILIPE PINTO MAGALHÃES (faturar em 6173)', 'luis.magalhaes@valmagal.pt', NULL, NULL, NULL, NULL, NULL, '5430-601 vassal', NULL, NULL, 'Brasil', NULL, 'active', 'bd_320'),
    ('ANDRE', 'THIEGO DE OLIVEIRA SITTA', 'thiegositta40@gmail.com', NULL, NULL, NULL, NULL, NULL, '35-041 MARBURG - ALEMANHA', NULL, NULL, 'Brasil', NULL, 'active', 'bd_321'),
    ('RUI', 'TIAGO BRANCO LIMA', 'GOR_DINHO@OUTLOOK.PT', NULL, NULL, NULL, NULL, NULL, '5328-AV ROSSUM - PAISES BAIXOS', NULL, NULL, 'Brasil', NULL, 'active', 'bd_322'),
    ('ERIC', 'GOMES E SUZELLI PIMENTEL', 'ericgcrs@gmail.com', NULL, NULL, NULL, NULL, NULL, '4700-284 BRAGA', NULL, NULL, 'Brasil', NULL, 'active', 'bd_323'),
    ('DANIELLY', 'ALVES RIBEIRO ROCHA', 'RIBEIRODANY2018@GMAIL.COM', NULL, NULL, NULL, NULL, NULL, '4715-594 BRAGA', NULL, NULL, 'Brasil', NULL, 'active', 'bd_324'),
    ('SORAIA', 'DE JESUS  GÓIS CHORA', 'SORAIA479@GMAUL.COM', NULL, NULL, NULL, NULL, NULL, 'IP2-9YY IPSWICH - REINO UNIDO', NULL, NULL, 'Brasil', NULL, 'active', 'bd_325'),
    ('PEDRO', 'JORGE DA SILVA MORAIS', NULL, NULL, NULL, NULL, NULL, NULL, '4880-314 VILARINHO', NULL, NULL, 'Brasil', NULL, 'active', 'bd_326'),
    ('FABIO', 'RAFAEL PINTO DE CASTRO', 'CROKZFABIOCASTRO@GMAIL.COM', NULL, NULL, NULL, NULL, NULL, '4425-235 ALFENA', NULL, NULL, 'Brasil', NULL, 'active', 'bd_327'),
    ('SARAH', 'KRISTIN GROB TOMAZ', 'S.GROBTOMAZ@GMAIL.COM', NULL, NULL, NULL, NULL, NULL, '848-3 KOLLBRUNN SUIÇA', NULL, NULL, 'Brasil', NULL, 'active', 'bd_328'),
    ('ALAN', 'GOULART PEREIRA', 'alangoulart100@gmail.com', NULL, NULL, NULL, NULL, NULL, 'NW10-2EJ REINO UNIDO', NULL, NULL, 'Brasil', NULL, 'active', 'bd_329'),
    ('ISMAEL', 'ANTÓNIO RAMALHO FERREIRA', 'anavilasboas@msn.com', NULL, NULL, NULL, NULL, NULL, '89-52 SCHLIETEN - SUIÇA', NULL, NULL, 'Brasil', NULL, 'active', 'bd_330'),
    ('VÍTOR', 'MANUEL DOS SANTOS LOUREIRO', 'vitorloureiro69@gmail.com', NULL, NULL, NULL, NULL, NULL, '2835-121 BAIXA DA BANHEIRA', NULL, NULL, 'Brasil', NULL, 'active', 'bd_331'),
    ('YANETH', 'MARIA RODRIGUES RODRIGUES GOMES - (6982 - JOSÉ NORBERTO DE GÓIS GOMES)', 'YMARIARR@HOTMAIL.COM', NULL, NULL, NULL, NULL, NULL, '2100-0 FRANCE', NULL, NULL, 'Brasil', NULL, 'active', 'bd_332'),
    ('DANIELLE', 'SANTOS GOMES', 'DANIELLE1993GOMES@GMAIL.COM', NULL, NULL, NULL, NULL, NULL, '4935-580 CHAFÉ', NULL, NULL, 'Brasil', NULL, 'active', 'bd_333'),
    ('CLAUDE', 'BRAUN', 'braunclaude72@gmail.com', NULL, NULL, NULL, NULL, NULL, '4585-583 RECAREI PAREDES', NULL, NULL, 'Brasil', NULL, 'active', 'bd_334'),
    ('PAULO', 'ALEXANDRE SOARES DE BRITO', 'pbrito@gmail.com', NULL, NULL, NULL, NULL, NULL, '4450-790 MATOSINHOS', NULL, NULL, 'Brasil', NULL, 'active', 'bd_335'),
    ('MARIA', 'BERTA DE ARAÚJO SOARES DE BRITO', 'pbrito@gmail.com', NULL, NULL, NULL, NULL, NULL, '4450-790 MATOSINHOS', NULL, NULL, 'Brasil', NULL, 'active', 'bd_336'),
    ('ISABEL', 'MARLENE FERNANDES LOPES PINHEIRO', 'ISABELPINHEIRO1982@HOTMAIL.COM', NULL, NULL, NULL, NULL, NULL, '460072-3 AMARANTE', NULL, NULL, 'Brasil', NULL, 'active', 'bd_337'),
    ('JORGE', 'ANDRÉ MOREIRA DO SANTOS', 'jorge.dos.santos79@hotmail.com', NULL, NULL, NULL, NULL, NULL, '5000-033 ANDRÃES', NULL, NULL, 'Brasil', NULL, 'active', 'bd_338'),
    ('TORCATO', 'DA SILVA BARROS (pago por adelaide)', 'torcatofcp@hotmail.com', NULL, NULL, NULL, NULL, NULL, '4480-683 vila do conde', NULL, NULL, 'Brasil', NULL, 'active', 'bd_339'),
    ('SUSANA', 'ISABEL PIMENTA DOS SANTOS', 'SANTOSSUSANA1010@ICLOUD.COM', NULL, NULL, NULL, NULL, NULL, '5430-603 VASSAL', NULL, NULL, 'Brasil', NULL, 'active', 'bd_340'),
    ('DANIELLE', 'FINANCI LANDI', 'dani-voto@hotmail.com', NULL, NULL, NULL, NULL, NULL, '4490-476 POVOA DE VARZIM', NULL, NULL, 'Brasil', NULL, 'active', 'bd_341'),
    ('SOLANGE', 'FINANCI', NULL, NULL, NULL, NULL, NULL, NULL, '4490-476 povoa de varzim', NULL, NULL, 'Brasil', NULL, 'active', 'bd_342'),
    ('MAIRA', 'ALBUQUERQUE DOS SANTOS', 'MAYRAAPBS@GMAIL.COM', NULL, NULL, NULL, NULL, NULL, '3621-CT BREUKELEEN', NULL, NULL, 'Brasil', NULL, 'active', 'bd_343'),
    ('ADNESE', 'DA VERA CRUZ PEREIRA', 'NINIVCP@GMAIL.COM', NULL, NULL, NULL, NULL, NULL, 'F--54190 VILLERUPT - FRANÇA', NULL, NULL, 'Brasil', NULL, 'active', 'bd_344'),
    ('VÍTOR', 'MANUEL BARATA DOS REIS GRILO', 'VBGRILO@HOTMAIL.COM', NULL, NULL, NULL, NULL, NULL, '100-7 SUIÇA', NULL, NULL, 'Brasil', NULL, 'active', 'bd_345'),
    ('JOAQUIM', 'LUIS CORREIA DE FIGUEIREDO', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Brasil', NULL, 'active', 'bd_346'),
    ('PAULO', 'ROBERTO ARCANJO RIBEIRO JUNIOR (FILHO DO  5372)', 'JUNIOR_ARCANJO9@HOTMAIL.COM', NULL, NULL, NULL, NULL, NULL, '410012-8 PORTO', NULL, NULL, 'Brasil', NULL, 'active', 'bd_347'),
    ('WELLIGTON', 'SANTANA DE SOUZA', 'WEELLIGTONSANTANNA@GMAIL.COM', NULL, NULL, NULL, NULL, NULL, '120-2 SUISSE', NULL, NULL, 'Brasil', NULL, 'active', 'bd_348'),
    ('PAULA', 'CRISTINA FERNANDES DA CUNHA FÔLHA', 'PAULA1974CUNHA@GMAIL.COM', NULL, NULL, NULL, NULL, NULL, 'BULLE - SUÍÇA', NULL, NULL, 'Brasil', NULL, 'active', 'bd_349'),
    ('BÁRBARA', 'MAIA DE CASTRO SOUSA', 'BARBARAMAIACSOUSA@GMAIL.COM', NULL, NULL, NULL, NULL, NULL, '4400-382 VILA NOVA DE GAIA', NULL, NULL, 'Brasil', NULL, 'active', 'bd_350'),
    ('RUI', 'SILVESTRE MACHADO CARVALHO (MARIA GORETI MAGALHAES SANTOS)', 'RSMC92@GMAIL.COM', NULL, NULL, NULL, NULL, NULL, '4415-078 PEROSINHO', NULL, NULL, 'Brasil', NULL, 'active', 'bd_351'),
    ('EDSON', 'MARTINS DE ARAÚJO', 'FOXBEAR9876@YAHOO.COM', NULL, NULL, NULL, NULL, NULL, 'SW9-9UQ LONDRES - REINO UNIDO', NULL, NULL, 'Brasil', NULL, 'active', 'bd_352'),
    ('ANTÓNIO', 'MIGUEL SOUSA CUNHA (TRF M OU MME SOUSA)', 'MIGUEL-CIGANO@HOTMAIL.COM', NULL, NULL, NULL, NULL, NULL, '7497-0 MARIGNIER - FRANÇA', NULL, NULL, 'Brasil', NULL, 'active', 'bd_353'),
    ('MÓNICA', 'SUSANA BORGES DA FONSECA CUNHA (TRF M OU MME SOUSA)', 'miguel-cigano@hotmail.com', NULL, NULL, NULL, NULL, NULL, '7497-0 MARIGNIER - FRANÇA', NULL, NULL, 'Brasil', NULL, 'active', 'bd_354'),
    ('SUSANA', 'PATRÍCIA PINTO FERREIRA', 'SUSANA_FERREIRA13@GMAIL.COM', NULL, NULL, NULL, NULL, NULL, '7520-134 SINES', NULL, NULL, 'Brasil', NULL, 'active', 'bd_355'),
    ('LUIS', 'RIBEIRO OSVALDO ( FATURAR NA FICHA (6914)', 'PORRADALONDRES@HOTMAIL.COM', NULL, NULL, NULL, NULL, NULL, 'N17Q-W LONDON', NULL, NULL, 'Brasil', NULL, 'active', 'bd_356'),
    ('LUIS', 'CARLOS ROSA VIEGAS', 'viegasluis741@gmail.com', NULL, NULL, NULL, NULL, NULL, 'SUIÇA', NULL, NULL, 'Brasil', NULL, 'active', 'bd_357'),
    ('PAULO', 'MANUEL MONTEIRO DA COSTA', NULL, NULL, NULL, NULL, NULL, NULL, '4150-020 Porto', NULL, NULL, 'Brasil', NULL, 'active', 'bd_358'),
    ('SAFIRA', 'BASTOS VIEIRA', 'SAFIRABASTOSVIEIRA@HOTMAIL.COM', NULL, NULL, NULL, NULL, NULL, '10-18 SUIÇA', NULL, NULL, 'Brasil', NULL, 'active', 'bd_359'),
    ('ARTUR', 'FERNANDO RIBEIRO MOREIRA', 'MOREIRAARTUR962@GMAIL.COM', NULL, NULL, NULL, NULL, NULL, '4595-131 FRAZÃO', NULL, NULL, 'Brasil', NULL, 'active', 'bd_360'),
    ('ALEXANDRA', 'ISABEL DE ALMEIDA VICÊNCIO PEREIRA', 'alexandravicenciopereira@hotmail.com', NULL, NULL, NULL, NULL, NULL, '28-00 DELÉMONT - SUIÇA', NULL, NULL, 'Brasil', NULL, 'active', 'bd_361'),
    ('ANTÓNIO', 'DAVID PERES RODRIGUES (VALERIA VIEIRA MARTINS 6559)', 'DAVIDRODRIGUES_46@HOTMAIL.COM', NULL, NULL, NULL, NULL, NULL, '23-00 SUIÇA', NULL, NULL, 'Brasil', NULL, 'active', 'bd_362'),
    ('MARLENE', 'MARIA LEMOS RIBEIRO', 'MARLENE.COMVAZ@HOTMAIL.COM', NULL, NULL, NULL, NULL, NULL, '4815-621 REGILDE', NULL, NULL, 'Brasil', NULL, 'active', 'bd_363'),
    ('CARLA', 'ALEXANDRA FRANGAO', 'CARLA-FRANGAO@HOTMAIL.COM', NULL, NULL, NULL, NULL, NULL, '1723-XX MARLY', NULL, NULL, 'Brasil', NULL, 'active', 'bd_364'),
    ('ANA', 'PATRÍCIA SIMÕES RAMOS', 'ANAPSRAMOS1978@GMAIL.COM', NULL, NULL, NULL, NULL, NULL, '4150-748 PORTO', NULL, NULL, 'Brasil', NULL, 'active', 'bd_365'),
    ('JOÃO', 'FILIPE RIBEIRO MARTINS', 'CERVA_FIL@HOTMAIL.COM', NULL, NULL, NULL, NULL, NULL, 'L766-3 LUXEMBURGO', NULL, NULL, 'Brasil', NULL, 'active', 'bd_366'),
    ('CLÁUDIA', 'MARIA NEVES MOREIRA DA ROCHA', 'MARIADAROCHA9041@GMAIL.COM', NULL, NULL, NULL, NULL, NULL, '1694-000 LENTIGNY - SUIÇA', NULL, NULL, 'Brasil', NULL, 'active', 'bd_367'),
    ('CARLOS', 'HUGO GOMES', 'carloshugogomes41@gmail.com', NULL, NULL, NULL, NULL, NULL, 'JE2-4P2 ST.HELIER, JERSEY', NULL, NULL, 'Brasil', NULL, 'active', 'bd_368'),
    ('NUNO', 'MIGUEL BRAZ LOPES', 'tikomacab@hotmail.com', NULL, NULL, NULL, NULL, NULL, '186-8 CALLAMBEY - SUIÇA', NULL, NULL, 'Brasil', NULL, 'active', 'bd_369'),
    ('LUANA', 'FILIPA PIMENTA LUCAS', 'LUANA.LUCAS25@HOTMAIL.COM', NULL, NULL, NULL, NULL, NULL, '2835-339 LAVRADIO', NULL, NULL, 'Brasil', NULL, 'active', 'bd_370'),
    ('MICHELLE', 'DA COSTA GOIS FERRAREZI', 'MICHELLE.GOIS@HOTMAIL.COM', NULL, NULL, NULL, NULL, NULL, '4400-107 VILA NOVA DE GAIA', NULL, NULL, 'Brasil', NULL, 'active', 'bd_371'),
    ('ALENDOÍZA', 'EPITÁCIO FERNANDES', 'ISADORAFERNANDES40@GMAIL.COM', NULL, NULL, NULL, NULL, NULL, '1885-053 Moscavide', NULL, NULL, 'Brasil', NULL, 'active', 'bd_372'),
    ('CLÁUDIO', 'GOMES DE SOUZA', 'ESCORPIAO1311@HOTMAIL.COM', NULL, NULL, NULL, NULL, NULL, '800-8 ZURICH - SUIÇA', NULL, NULL, 'Brasil', NULL, 'active', 'bd_373'),
    ('ARTHUR', 'GEORGE SILVA DA ROSA', 'art.rosa@gmail.com', NULL, NULL, NULL, NULL, NULL, '4490-634 POVOA VARZIM', NULL, NULL, 'Brasil', NULL, 'active', 'bd_374'),
    ('MARCO', 'PAULO DE OLIVEIRA NEVES', 'MARCONEVES1980@HOTMAIL.COM', NULL, NULL, NULL, NULL, NULL, '4420-392 VALBOM', NULL, NULL, 'Brasil', NULL, 'active', 'bd_375'),
    ('ANTÓNIO', 'PINTO TEIXEIRA (4193-MARY FLOR REJAS CALLE)', 'ANTONIO.PINTOTEIXEIRAGPI@GMAIL.COM', NULL, NULL, NULL, NULL, NULL, '120-2 GENÈVE', NULL, NULL, 'Brasil', NULL, 'active', 'bd_376'),
    ('ANTÓNIO', 'MIGUEL BROCHADO DE CAMPOS', 'CAMPOSMIGUEL1988@HOTMAIL.COM', NULL, NULL, NULL, NULL, NULL, '4890-503 PAÇÔ', NULL, NULL, 'Brasil', NULL, 'active', 'bd_377'),
    ('SAMUEL', 'GONÇALVES DE SOUZA', NULL, NULL, NULL, NULL, NULL, NULL, '4585-899 PAREDES', NULL, NULL, 'Brasil', NULL, 'active', 'bd_378'),
    ('LUÍS', 'MANUEL DIAS', 'LUISIWANT@GMAIL.COM', NULL, NULL, NULL, NULL, NULL, '4425-179 MAIA', NULL, NULL, 'Brasil', NULL, 'active', 'bd_379'),
    ('TIAGO', 'JORGE FERREIRA MARQUES RODRIGUES', 'RODRIGUESTTS123@GMAIL.COM', NULL, NULL, NULL, NULL, NULL, '2625-138 PÓVOA DE SANTA IRIA', NULL, NULL, 'Brasil', NULL, 'active', 'bd_380'),
    ('CARLOS', 'EDUARDO FERREIRA BATISTA', 'CARLOS.KAKA.199626@GMAIL.COM', NULL, NULL, NULL, NULL, NULL, '7520-135 SINES', NULL, NULL, 'Brasil', NULL, 'active', 'bd_381'),
    ('LUÍS', 'MIGUEL DE OLIVEIRA SANTOS', 'luis.miguel.lm84@gmail.com', NULL, NULL, NULL, NULL, NULL, '3720-821 CUCUJÃES', NULL, NULL, 'Brasil', NULL, 'active', 'bd_382'),
    ('DANIEL', 'ALBERTINO FERREIRA DE CASTRO', 'DANIELCASTRO21C@GAMIL.COM', NULL, NULL, NULL, NULL, NULL, '4615-604 LIXA', NULL, NULL, 'Brasil', NULL, 'active', 'bd_383'),
    ('HÉLDER', 'ALEXANDRE MACHADO DE ALMEIDA', 'HELDERALEXANDREMACHADO@HOTMAIL.COM', NULL, NULL, NULL, NULL, NULL, '4590-066 CARVALHOSA', NULL, NULL, 'Brasil', NULL, 'active', 'bd_384'),
    ('CLÁUDIO', 'ANDRÉ NEVES CORDEIRO', 'claudioancordeiro@hotmail.com', NULL, NULL, NULL, NULL, NULL, '396-0 SIERRE - SUIÇA', NULL, NULL, 'Brasil', NULL, 'active', 'bd_385'),
    ('ALBERTO', 'NUNO PINTO PEREIRA', 'alexandravicenciopereira@hotmail.com', NULL, NULL, NULL, NULL, NULL, '280-0 DELÉMONT - SUÍÇA', NULL, NULL, 'Brasil', NULL, 'active', 'bd_386'),
    ('MARIA', 'JOÃO DUARTE ALCAIDE CARNEIRO DE ALMEIDA RIAZ', 'JUEMARTINHO@GMAIL.COM', NULL, NULL, NULL, NULL, NULL, '8500-423 PORTIMÃO', NULL, NULL, 'Brasil', NULL, 'active', 'bd_387'),
    ('DANIEL', 'HENRIQUE SILVA MARTINS (PAGO POR RITA FERNANDES)', 'DAARITA56@GMAIL.COM', NULL, NULL, NULL, NULL, NULL, '4730-782 VILA VERDE', NULL, NULL, 'Brasil', NULL, 'active', 'bd_388'),
    ('EDUARDO', 'MANUEL VILELA SERQUEIRA', 'EDUARDOSERQUEIRA@HOTMAIL.COM', NULL, NULL, NULL, NULL, NULL, '7501-8 PARIS', NULL, NULL, 'Brasil', NULL, 'active', 'bd_389'),
    ('JOSÉ', 'CARLOS RAMOS RUSSO', 'RUSSOJOSE234@GMAIL.COM', NULL, NULL, NULL, NULL, NULL, '4425-616 MAIA', NULL, NULL, 'Brasil', NULL, 'active', 'bd_390'),
    ('MIKAEL', 'BRAUN', 'MIKAELBRAUN1925@GMAIL.COM', NULL, NULL, NULL, NULL, NULL, '405042-4 PORTO', NULL, NULL, 'Brasil', NULL, 'active', 'bd_391'),
    ('EDNA', 'DE OLIVEIRA', 'DINA_OLIVEIRA1973@HOTMAIL.COM', NULL, NULL, NULL, NULL, NULL, '758014-3 BAIRRO S FRANCISCO ALCACER DO SAL', NULL, NULL, 'Brasil', NULL, 'active', 'bd_392'),
    ('ELÍSIO', 'MANUEL DA SILVA BARBOSA', 'CONTACT.ELISIO@GMAIL.COM', NULL, NULL, NULL, NULL, NULL, '7565-0 BEYNES', NULL, NULL, 'Brasil', NULL, 'active', 'bd_393'),
    ('NUNO', 'MIGUEL DUARTE', 'RODBRU@LIVE.COM', NULL, NULL, NULL, NULL, NULL, '7570-789 TROIA', NULL, NULL, 'Brasil', NULL, 'active', 'bd_394'),
    ('UIRIS', 'JOSÉ GONÇALVES BRITO', 'UIRISNENE7@GMAIL.COM', NULL, NULL, NULL, NULL, NULL, '2330-315 ENTRONCAMENTO', NULL, NULL, 'Brasil', NULL, 'active', 'bd_395'),
    ('ISABELLE', 'MARIE REINE KATIA JOUANNEL (SERGIO MANUEL PEREIRA DOS SANTOS)', 'POLISSEURDU18@GMAIL.COM', NULL, NULL, NULL, NULL, NULL, '1800-0 FRANCE', NULL, NULL, 'Brasil', NULL, 'active', 'bd_396'),
    ('PATRÍCIA', 'SUSANA CARDOSO DA SILVA', 'PATRICIA-SUSANA08@HOTMAIL.COM', NULL, NULL, NULL, NULL, NULL, '4535-193 MOZELOS', NULL, NULL, 'Brasil', NULL, 'active', 'bd_397'),
    ('MARIA', 'ANTÓNIA SILVA TEOPISTO', 'RIKARDINATEOPISTO33@HOTMAIL.COM', NULL, NULL, NULL, NULL, NULL, '2000-493 PERNES', NULL, NULL, 'Brasil', NULL, 'active', 'bd_398'),
    ('JOAO', 'PAULO PINHEIRO DIAS (ISABEL MARIA DE SOUSA PINHEIRO DIAS)', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Brasil', NULL, 'active', 'bd_399'),
    ('ISABEL', 'MARIA DE SOUSA PINHEIRO DIAS', 'ISABELPINHEIRODIAS@GMAIL.COM', NULL, NULL, NULL, NULL, NULL, '4425-179 MAIA', NULL, NULL, 'Brasil', NULL, 'active', 'bd_400'),
    ('HELEN', 'CRISTINA DE AGUIAR (FATURAR EM FICHA DE JOSÉ MANUEL LEITE 120)', 'HELENCRISBELGICA@GMAIL.COM', NULL, NULL, NULL, NULL, NULL, '4820-286 FAFE', NULL, NULL, 'Brasil', NULL, 'active', 'bd_401'),
    ('ANA', 'FILIPA GOUVEIA PARRA', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Brasil', NULL, 'active', 'bd_402'),
    ('EDUARDO', 'MANUEL COSTA MARQUES', '1975MARQUESEDU@GMAIL.COM', NULL, NULL, NULL, NULL, NULL, '5488-0 HUSSIGNY', NULL, NULL, 'Brasil', NULL, 'active', 'bd_403'),
    ('JOSÉ', 'MANUEL ALMEIDA ENES', 'enes.valongo@outlook.pt', NULL, NULL, NULL, NULL, NULL, '17-35 GIFFERS SUIÇA', NULL, NULL, 'Brasil', NULL, 'active', 'bd_404'),
    ('LUCIMAR', 'RIBEIRO  (TF em nome Marcos Amiga Are - AMANCIO)', 'LUCRIBEIRO1969@HOTMAIL.COM', NULL, NULL, NULL, NULL, NULL, '116-2 SAN PRES - SUIÇA', NULL, NULL, 'Brasil', NULL, 'active', 'bd_405'),
    ('HÉLDER', 'ANTÓNIO DOS SANTOS ÁVILA BRUM', 'HASABRUM@HOTMAIL.COM', NULL, NULL, NULL, NULL, NULL, 'M8V-OC7 ETOBICOKE', NULL, NULL, 'Brasil', NULL, 'active', 'bd_406'),
    ('INÊS', 'MARGARIDA ANTUNES MARTINS', 'MARTINS.INNES.37@GMAIL.COM', NULL, NULL, NULL, NULL, NULL, '273-8 SUIÇA', NULL, NULL, 'Brasil', NULL, 'active', 'bd_407'),
    ('PATRICIA', 'GOMES BATISTA', 'PATRICIA-GU2014@OUTLOOK.COM', NULL, NULL, NULL, NULL, NULL, '840-6 WINTERTHUR, ZURICK SUIÇA', NULL, NULL, 'Brasil', NULL, 'active', 'bd_408'),
    ('MÁRIO', 'WILSON RAFAEL DE PINA', 'm.wils@hotmail.com', NULL, NULL, NULL, NULL, NULL, 'EC1R-0WX SKINNER STREET - ISLINGTON - LONDRES', NULL, NULL, 'Brasil', NULL, 'active', 'bd_409'),
    ('NADIR', 'FATIMA LOPES ARAÚJO', 'ARAUJOLUIS@MSN.COM', NULL, NULL, NULL, NULL, NULL, '4760-470 FRADELOS - VILA NOVA DE FAMALICÃO', NULL, NULL, 'Brasil', NULL, 'active', 'bd_410'),
    ('FELISBERTO', 'DA SILVA E SÁ', 'felisbertomen@gmail.com', NULL, NULL, NULL, NULL, NULL, '4745-532 SÃO ROMÃO DO CORONADO', NULL, NULL, 'Brasil', NULL, 'active', 'bd_411'),
    ('ALEXANDRE', 'BECCA', 'BECCAALE37@GMAIL.COM', NULL, NULL, NULL, NULL, NULL, '4705-225 BRAGA', NULL, NULL, 'Brasil', NULL, 'active', 'bd_412'),
    ('ANTONIO', 'MANUEL OLIVEIRA TEIXEIRA', 'KALANGA1987@GMAIL.COM', NULL, NULL, NULL, NULL, NULL, 'SUIÇA', NULL, NULL, 'Brasil', NULL, 'active', 'bd_413'),
    ('JOSE', 'ANTONIO FARINHO NETO', 'joseantoniofnetela@gmail.com', NULL, NULL, NULL, NULL, NULL, '11-90 FOREST BRUXELAS - BÉLGICA', NULL, NULL, 'Brasil', NULL, 'active', 'bd_414'),
    ('CID', 'CORREA DO NASCIMENTO', 'JUCACARICA@HOTMAIL.COM', NULL, NULL, NULL, NULL, NULL, '120-1 GENEBRA SUIÇA', NULL, NULL, 'Brasil', NULL, 'active', 'bd_415'),
    ('BRUNO', 'TELMO RAMARIZ DA SILVA', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Brasil', NULL, 'active', 'bd_416'),
    ('ELIZEU', 'DE OLIVEIRA SILVA', 'ELIZEUOLIVER1983@GMAIL.COM', NULL, NULL, NULL, NULL, NULL, '280012-2 ALMADA', NULL, NULL, 'Brasil', NULL, 'active', 'bd_417'),
    ('JORGE', 'LUIZ DE JESUS CORREIA (cont.  PRISCILA RIBEIRO DA SILVEIRA)', 'JORGECORREIA79@HOTMAIL.COM', NULL, NULL, NULL, NULL, NULL, 'BISTROL', NULL, NULL, 'Brasil', NULL, 'active', 'bd_418'),
    ('JOAQUIM', 'ALEXANDRE BRANCO', 'joaquim-branco-@hotmail.com', NULL, NULL, NULL, NULL, NULL, '396-3 CRANS-MONTANA', NULL, NULL, 'Brasil', NULL, 'active', 'bd_419'),
    ('DAVID', 'JOAQUIM SALGUEIRO PINHEIRO', 'davidnet05@hotmail.fr', NULL, NULL, NULL, NULL, NULL, '052-00 ST SAUVEUR', NULL, NULL, 'Brasil', NULL, 'active', 'bd_420'),
    ('RONY', 'EVERSON CORREIA DA SILVA', 'EVERSON_RONY@HOTMAIL.COM', NULL, NULL, NULL, NULL, NULL, '2460-819 CARVALHAL', NULL, NULL, 'Brasil', NULL, 'active', 'bd_421'),
    ('RODRIGO', 'OLIVEIRA AIRES - CONTRATO EM NOME DA MÃE PATRICIA OLIVEIRA AIRES', 'RODRIGOAIRESPT@GMAIL.COM', NULL, NULL, NULL, NULL, NULL, '4430-642 VILA NOVA DE GAIA', NULL, NULL, 'Brasil', NULL, 'active', 'bd_422'),
    ('MARGARIDA', 'FERREIRA CORREIA (DD em nome do filho André Filipe Correia Reis', 'REISA13@HOTMAIL.COM', NULL, NULL, NULL, NULL, NULL, 'IP24-2DU THETFORD, NORFOLK, REINO UNIDO', NULL, NULL, 'Brasil', NULL, 'active', 'bd_423'),
    ('MARCO', 'ANDRÉ MARQUES', 'DURRERAG@HOTMAIL.COM', NULL, NULL, NULL, NULL, NULL, '895-3 DIETIKON', NULL, NULL, 'Brasil', NULL, 'active', 'bd_424'),
    ('GABRIELA', 'VERAS DE LIMA', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Brasil', NULL, 'active', 'bd_425'),
    ('DANIELA', 'DE OLIVEIRA SILVA (em nome do amigo flavio)', 'DANNY.HOLLANDA2018@GMAIL.COM', NULL, NULL, NULL, NULL, NULL, '4460-744 PORTO', NULL, NULL, 'Brasil', NULL, 'active', 'bd_426'),
    ('IONEL', 'MARCEL LAZUR (transplante capilar)', 'ionel21_marcel@hotmail.com', NULL, NULL, NULL, NULL, NULL, '2870-047 MONTIJO - PORTUGAL', NULL, NULL, 'Brasil', NULL, 'active', 'bd_427'),
    ('FABIO', 'ANTONIO GUEDES PEREIRA ALVES', 'FABIOGPALVES.18@GMAIL.COM', NULL, NULL, NULL, NULL, NULL, '4460-384 SAO MAMEDE INFESTA', NULL, NULL, 'Brasil', NULL, 'active', 'bd_428'),
    ('CONCEIÇÃO', 'DOS SANTOS NEVES', NULL, NULL, NULL, NULL, NULL, NULL, '2700-579 AMADORA', NULL, NULL, 'Brasil', NULL, 'active', 'bd_429'),
    ('HENRIQUE', 'MANUEL GOMES VALADARES', 'MARLENEPIRESGONCALVES1982@GMAIL.COM', NULL, NULL, NULL, NULL, NULL, 'PORTUGAL', NULL, NULL, 'Brasil', NULL, 'active', 'bd_430'),
    ('BRUNO', 'DANIEL DIAS CARVALHO', 'bcd18122012@gmail.com', NULL, NULL, NULL, NULL, NULL, '4475-716 Sao Pedro de Avioso', NULL, NULL, 'Brasil', NULL, 'active', 'bd_431'),
    ('ANA', 'LUISA GASPAR DIAS', 'luisadamiao@hotmail.com', NULL, NULL, NULL, NULL, NULL, '4500-416 ESPINHO', NULL, NULL, 'Brasil', NULL, 'active', 'bd_432'),
    ('ANDRÉ', 'FILIPE CORREIA REIS', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Brasil', NULL, 'active', 'bd_433'),
    ('LUCIANDERSON', 'ALVES ROSEMIRO', 'lulu.rosemiro@gmail.com', NULL, NULL, NULL, NULL, NULL, '10-50 IXELLES - BÉLGICA', NULL, NULL, 'Brasil', NULL, 'active', 'bd_434'),
    ('ROMÁRIO', 'FREITAS DE OLIVEIRA', 'ROMARIO.FREITAS9@ICLOUD.COM', NULL, NULL, NULL, NULL, NULL, '4400-264 VILA NOVA DE GAIA', NULL, NULL, 'Brasil', NULL, 'active', 'bd_435'),
    ('MANUEL', 'PEREIRA MIRANDA', 'NELO.PEREIRA.MIRANDA@GMAIL.COM', NULL, NULL, NULL, NULL, NULL, '3770-016 Quinta Nova', NULL, NULL, 'Brasil', NULL, 'active', 'bd_436'),
    ('ANTONIO', 'MANUEL OLIVEIRA MARQUES DA SILVA', 'TONACHA61@GMAIL.COM', NULL, NULL, NULL, NULL, NULL, '1495-081 Algés', NULL, NULL, 'Brasil', NULL, 'active', 'bd_437'),
    ('JOAQUIM', 'EMANUEL RIBEIRO GONÇALVES', 'KINELRIBEIRO@GMAIL.COM', NULL, NULL, NULL, NULL, NULL, '156-3 BELMONT BROYE - SUIÇA', NULL, NULL, 'Brasil', NULL, 'active', 'bd_438'),
    ('JOHN', 'MURRAY NICHOLAS', NULL, NULL, NULL, NULL, NULL, NULL, '97212-5143 PORTLAND, OR', NULL, NULL, 'Brasil', NULL, 'active', 'bd_439'),
    ('DOUGLAS', 'JONATHAN OLIVEIRA', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Brasil', NULL, 'active', 'bd_440'),
    ('ROSA', 'PATRICIA VIEIRA DE FREITAS (mãe Rosa Maria Gonçalves de Freitas)', 'R2VIEIRA20@GMAIL.COM', NULL, NULL, NULL, NULL, NULL, '4300-078 PORTO', NULL, NULL, 'Brasil', NULL, 'active', 'bd_441'),
    ('SANDRO', 'MIGUEL DOS SANTOS RODRIGUES', 'SANDRO_MIGUEL77@HOTMAIL.CO.UK', NULL, NULL, NULL, NULL, NULL, 'BH11-9HB DORSET, BOURNEMOTH UK', NULL, NULL, 'Brasil', NULL, 'active', 'bd_442'),
    ('RUTE', 'CATARINA DOS SANTOS CONDE', 'conderute@gmail.com', NULL, NULL, NULL, NULL, NULL, '1908 RIDDES-SUISSE', NULL, NULL, 'Brasil', NULL, 'active', 'bd_443'),
    ('VAGNER', 'ALMEIDA MARTINS e ALINE GIMENES MARTINS (contrato de transplante capilar de dermato)', NULL, NULL, NULL, NULL, NULL, NULL, '4465-280 SÃO MAMEDE DE INFESTA', NULL, NULL, 'Brasil', NULL, 'active', 'bd_444'),
    ('joaquim', 'ruivo', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Brasil', NULL, 'active', 'bd_445'),
    ('ILÍDIA', 'SOFIA PINTO CORREIA RIBEIRO', 'ilidiacorreia1994@gmail.com', NULL, NULL, NULL, NULL, NULL, '4400-374 VILA NOVA DE GAIA', NULL, NULL, 'Brasil', NULL, 'active', 'bd_446'),
    ('CERIANI', 'OLIVIER LUDOVIC (JAIME KIAMY CANEIRO)', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Brasil', NULL, 'active', 'bd_447'),
    ('IOLANDA', 'TÂNIA FREITAS DE SOUSA', 'VIVERMATA@HOTMAIL.COM', NULL, NULL, NULL, NULL, NULL, 'TS 178D-D STOCKTON ON TEES - S', NULL, NULL, 'Brasil', NULL, 'active', 'bd_448'),
    ('SARA', 'CRISTINA SANTOS', 'SARASLBPIKI@GMAIL.COM', NULL, NULL, NULL, NULL, NULL, 'TA201H-G SOMERSET', NULL, NULL, 'Brasil', NULL, 'active', 'bd_449'),
    ('NUNO', 'RICARDO PEREIRA', 'NUNOSOARES77—@HOTMAIL.COM', NULL, NULL, NULL, NULL, NULL, '372077-1 OLIVEIRA DE AZEMEIS', NULL, NULL, 'Brasil', NULL, 'active', 'bd_450'),
    ('FABIANA', 'RAMOS MARTINS', 'fabiana4335554@icloud.com', NULL, NULL, NULL, NULL, NULL, '4150-748 porto', NULL, NULL, 'Brasil', NULL, 'active', 'bd_451'),
    ('CARLOS', 'MANUEL TAVARES GUIMARAES', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Brasil', NULL, 'active', 'bd_452'),
    ('ZEFERINO', 'MANUEL CORREIA DA COSTA', 'ZEFERINOCOSTA28@GMAIL.COM', NULL, NULL, NULL, NULL, NULL, '4825-083 ÁGUA LONGA', NULL, NULL, 'Brasil', NULL, 'active', 'bd_453'),
    ('JOSÉ', 'PAULO DA COSTA RIBEIRO', 'josepcribeiro@hotmail.com', NULL, NULL, NULL, NULL, NULL, 'FAFE', NULL, NULL, 'Brasil', NULL, 'active', 'bd_454'),
    ('CARLA', 'SOFIA DE PEDROSO FERREIRA', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Brasil', NULL, 'active', 'bd_455'),
    ('GUILHERME', 'VINICIUS CORREA', 'GUILHERMEVINICIUS.GV@HOTMAIL.COM', NULL, NULL, NULL, NULL, NULL, 'LISBOA - PORTUGAL', NULL, NULL, 'Brasil', NULL, 'active', 'bd_456'),
    ('DEBORA', 'FERNANDES MANUEL POMBO', 'DEBORAPOMBO0000@ICLOUD.COM', NULL, NULL, NULL, NULL, NULL, 'Amadora - PORTUGAL', NULL, NULL, 'Brasil', NULL, 'active', 'bd_457'),
    ('DORA', 'CRISTINA MOREIRA BRITO', 'doracaj80@gmail.com', NULL, NULL, NULL, NULL, NULL, 'BASEL - SUIÇA', NULL, NULL, 'Brasil', NULL, 'active', 'bd_458'),
    ('RUI', 'MIGUEL BEIRAO SARAFANA', 'ruisarafana@outlook.com', NULL, NULL, NULL, NULL, NULL, 'DIFFERDANGE - LUXEMBURGO', NULL, NULL, 'Brasil', NULL, 'active', 'bd_459'),
    ('MARIA', 'OTILIA BELCHIOR DA SILVA', 'belchiormariaig@icloud.com', NULL, NULL, NULL, NULL, NULL, 'DIFFERDANGE - LUXEMBURGO', NULL, NULL, 'Brasil', NULL, 'active', 'bd_460'),
    ('HUGO', 'SANTOS CÉSAR', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Brasil', NULL, 'active', 'bd_461'),
    ('DOMINGOS', 'FILIPE MESTRE DOIDINHO', 'DOMINGOS_FILIPE_TORRES_22@HOTMAIL.COM', NULL, NULL, NULL, NULL, NULL, 'BRIENZ - SUIÇA', NULL, NULL, 'Brasil', NULL, 'active', 'bd_462'),
    ('HELENA', 'VALENTE GIL SULEMANI', 'helenav_gil@hotmail.com', NULL, NULL, NULL, NULL, NULL, 'FULLY', NULL, NULL, 'Brasil', NULL, 'active', 'bd_463'),
    ('JOSE', 'LINDO PEREIRA LOPES', 'JOSELOPESCV10@GMAIL.COM', NULL, NULL, NULL, NULL, NULL, '2700-575 Amadora', NULL, NULL, 'Brasil', NULL, 'active', 'bd_464'),
    ('SÓNIA', 'BORGES ROCHA', 'SONIABORGESROCHA52@GMAIL.COM', NULL, NULL, NULL, NULL, NULL, '2700-575 Amadora', NULL, NULL, 'Brasil', NULL, 'active', 'bd_465'),
    ('MARIA', 'AMELIA FERREIRA COELHO (SEM CONTRATO)', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Brasil', NULL, 'active', 'bd_466'),
    ('SARA', 'CRISTINA FERNANDES MORENO', 'morenocristina007@gmail.com', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Brasil', NULL, 'active', 'bd_467'),
    ('IRANILDA', 'CARDOSO MELO', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Brasil', NULL, 'active', 'bd_468'),
    ('ANA', 'FILIPA GIGANTE MALHOU', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Brasil', NULL, 'active', 'bd_469'),
    ('SUSANA', 'MARGARIDA RIBEIRO ALVES', 'rubenfidalgo20@gmail.com', NULL, NULL, NULL, NULL, NULL, 'Quintã de Pêro Martins', NULL, NULL, 'Brasil', NULL, 'active', 'bd_470'),
    ('RÚBEN', 'ANTÓNIO FIDALGO ALMEIDA', 'rubenfidalgo29@gmail.com', NULL, NULL, NULL, NULL, NULL, 'Quintã de Pêro Martins', NULL, NULL, 'Brasil', NULL, 'active', 'bd_471'),
    ('ANDRE', 'MIGUEL CANCELA DE JESUS', 'andrejesus26@hotmail.com', NULL, NULL, NULL, NULL, NULL, 'PORTO - PORTUGAL', NULL, NULL, 'Brasil', NULL, 'active', 'bd_472'),
    ('NUNO', 'GONÇALO MARQUES SALCEDAS', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Brasil', NULL, 'active', 'bd_473'),
    ('ISABEL', 'JOANA ANDRADE', 'otiliaandradesantos84@gmail.com', NULL, NULL, NULL, NULL, NULL, 'TALAÍDE - PORTUGAL', NULL, NULL, 'Brasil', NULL, 'active', 'bd_474'),
    ('MARCIA', 'CRISTINA BATISTA SCHUH', 'marciaschuh@hotmail.com', NULL, NULL, NULL, NULL, NULL, 'MADRID - ESPANHA', NULL, NULL, 'Brasil', NULL, 'active', 'bd_475'),
    ('ADRIANE', 'NARCIO MATE  (JOSE BERNARDINO TEIXEIRA DE ABREu)', 'JOSEABREU1980@HOTMAIL.COM', NULL, NULL, NULL, NULL, NULL, 'Zürich, Suíça', NULL, NULL, 'Brasil', NULL, 'active', 'bd_476'),
    ('SORAYA', 'FREY', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Brasil', NULL, 'active', 'bd_477'),
    ('ILIDIO', 'MIGUEL RODRIGUES MARQUES', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Brasil', NULL, 'active', 'bd_478'),
    ('GUILHERME', 'BALBINOT e ROCHELE BEN DUARTE', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Brasil', NULL, 'active', 'bd_479'),
    ('MARIA', 'SOLANGE POLATTI', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Brasil', NULL, 'active', 'bd_480'),
    ('JULIO', 'CESAR PARPINELLI', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Brasil', NULL, 'active', 'bd_481'),
    ('MADALENA', 'MARIA FREIRE DE JESUS DOS REIS BORGES', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Brasil', NULL, 'active', 'bd_482'),
    ('ANA', 'MARÍLIA SILVA GOMES SOARES', 'ANA.MARILIA40@ICLOUD.COM', NULL, NULL, NULL, NULL, NULL, 'LE BUISSON DE CADOUIN', NULL, NULL, 'Brasil', NULL, 'active', 'bd_483'),
    ('MARCO', 'JOSÉ LOBAO PAULA AREIAS', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Brasil', NULL, 'active', 'bd_484'),
    ('VANESSA', 'KARITA DA SILVA SAES', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Brasil', NULL, 'active', 'bd_485'),
    ('RICARDO', 'MIGUEL ALVES PEREIRA (CAPILAR)', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Brasil', NULL, 'active', 'bd_486'),
    ('EDNA', 'DE FREITAS PARPINELLI', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Brasil', NULL, 'active', 'bd_487'),
    ('DILVANA', 'KATIA PALUDOS', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Brasil', NULL, 'active', 'bd_488'),
    ('CLARISSE', 'ALEIXO OLIVEIRA NETO', 'CLARISSE_97_NETINHA@HOTMAIL.COM', NULL, NULL, NULL, NULL, NULL, 'AVEIRO', NULL, NULL, 'Brasil', NULL, 'active', 'bd_489'),
    ('MARIA', 'GORETE DOS REIS DA COSTA', 'ORTAIS19@HOTMAIL.COM', NULL, NULL, NULL, NULL, NULL, 'ROUBAIX', NULL, NULL, 'Brasil', NULL, 'active', 'bd_490'),
    ('PAULA', 'CRISTINA DA CUNHA SANTO', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Brasil', NULL, 'active', 'bd_491'),
    ('RAFAEL', 'LIMA DOS SANTOS', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Brasil', NULL, 'active', 'bd_492'),
    ('ALEXSANDRO', 'DOS SANTOS MOURA', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Brasil', NULL, 'active', 'bd_493'),
    ('JESSICA', 'ALEXANDRA OLIVEIRA', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Brasil', NULL, 'active', 'bd_494'),
    ('LEIDIMARA', 'COSTA FONSECA', 'LEIDIMARACOSTAFONSECA@gmail.com', NULL, NULL, NULL, NULL, NULL, 'Paivas', NULL, NULL, 'Brasil', NULL, 'active', 'bd_495'),
    ('RICARDO', 'MANUEL ANDRADE DE OLIVEIRA', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Brasil', NULL, 'active', 'bd_496'),
    ('CLAUDIO', 'OLIVEIRA', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Brasil', NULL, 'active', 'bd_497'),
    ('MARIA', 'DA CONCEIÇÃO PEREIRA ANDRADE', 'ANDRADEMARIA82@HOTMAIL.COM', NULL, NULL, NULL, NULL, NULL, 'PARCE SUR SARTHE', NULL, NULL, 'Brasil', NULL, 'active', 'bd_498'),
    ('ALZIRA', 'DO CARMO LOPES DA SILVA FERREIRA', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Brasil', NULL, 'active', 'bd_499'),
    ('FERNANDO', 'HENRIQUE DUTRA DIAS', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Brasil', NULL, 'active', 'bd_500'),
    ('RAFAEL', 'POTRICH DOS REIS  (DILVANA PALUDO)', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Brasil', NULL, 'active', 'bd_501'),
    ('MARIA', 'LUÍSA NETO DA SILVA', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Brasil', NULL, 'active', 'bd_502'),
    ('MANUEL', 'ANTONIO SOUTELO PEREIRA', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Brasil', NULL, 'active', 'bd_503'),
    ('FABIO', 'PAULO PONTE', 'fabioponte75@gmail.com', NULL, NULL, NULL, NULL, NULL, 'Funchal', NULL, NULL, 'Brasil', NULL, 'active', 'bd_504'),
    ('PAULO', 'CESAR MOREIRA DE LIMA', 'TUTUMOREIRALIMA@GMAIL.COM', NULL, NULL, NULL, NULL, NULL, 'COIMBRA', NULL, NULL, 'Brasil', NULL, 'active', 'bd_505'),
    ('ANDRÉ', 'GUSTAVO SOUSA AMORIM', 'AGSA070775@GMAIL.COM', NULL, NULL, NULL, NULL, NULL, 'Amriswil', NULL, NULL, 'Brasil', NULL, 'active', 'bd_506'),
    ('SANDRA', 'MÓNICA MADUREIRA DE ALMEIDA VIEIRA', NULL, NULL, NULL, NULL, NULL, NULL, 'Meaux', NULL, NULL, 'Brasil', NULL, 'active', 'bd_507'),
    ('ALUIZIO', 'CAFFE ALVES SOBRINHO', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Brasil', NULL, 'active', 'bd_508'),
    ('CÉLINE', 'GISELENE RIBEIRO  (cont: VIRGÍNIA MARIA ABREU DA CUNHA RIBEIRO - 9276', 'celina.ribeiro203@gmail.com', NULL, NULL, NULL, NULL, NULL, 'Guimarães', NULL, NULL, 'Brasil', NULL, 'active', 'bd_509'),
    ('JOSÉ', 'AUGUSTO PINA DO NASCIMENTO', 'j.donascimento@sfr.fr', NULL, NULL, NULL, NULL, NULL, 'ST PANTALEON', NULL, NULL, 'Brasil', NULL, 'active', 'bd_510'),
    ('RAÚL', 'EVANDRO PEREIRA DIAS MONTEIRO', 'rauldiasmonteiro@gmail.com', NULL, NULL, NULL, NULL, NULL, 'Vila Nova de Gaia', NULL, NULL, 'Brasil', NULL, 'active', 'bd_511')
ON CONFLICT (external_id) DO UPDATE SET
    first_name = EXCLUDED.first_name,
    last_name = EXCLUDED.last_name,
    email = EXCLUDED.email,
    phone = EXCLUDED.phone,
    mobile = EXCLUDED.mobile,
    updated_at = NOW();